/* Post-file hub + Intuit Agent Chat prototype.
 *
 * Every $ figure comes from window.AOS_DATA (generated by ui/build_data.py
 * from calculators/) — the chat script formats, it never computes tax math.
 * Conversation follows the Detect Agent protocol:
 * Hook → Onboard (2 Qs) → Plan (ranked, ≤4) → Assess → Act doors → Wrap.
 */
(function () {
  // Which return is loaded: ?customer=<id> wins, else the manifest default,
  // else the bundled single-customer AOS_DATA (e.g. file:// with no picker).
  const RET = window.AOS_RETURNS || null;
  function pickActiveId() {
    if (!RET || !RET.data) return null;
    const q = new URLSearchParams(window.location.search).get("customer");
    if (q && RET.data[q]) return q;
    if (RET.active_default && RET.data[RET.active_default]) return RET.active_default;
    return Object.keys(RET.data)[0] || null;
  }
  const ACTIVE = pickActiveId();
  // Intro A/B for user testing: "full" (five-block) vs "lean" (Amy's WIP:
  // hero → framing → 3 questions → plan w/ one-line how-to per move).
  const INTRO_VARIANT = (new URLSearchParams(window.location.search).get("intro") === "lean" || window.AOS_INTRO_VARIANT === "lean") ? "lean" : "full";
  const D = (RET && ACTIVE && RET.data[ACTIVE]) ? RET.data[ACTIVE] : window.AOS_DATA;
  const CUST = D.customer;
  const SHOWN = D.analysis.shown;

  const $ = (id) => document.getElementById(id);
  const log = $("chat-log");
  const chipsEl = $("chips");
  const scroller = $("chat-scroll");

  // ---------- formatting ----------
  const exact = (n) => "$" + Math.round(n).toLocaleString("en-US");
  const friendly = (n) => "$" + (Math.round(n / 100) * 100).toLocaleString("en-US");
  const compact = (n) => "$" + (Math.abs(n) >= 1000 ? Math.round(n / 1000) + "K" : String(Math.round(n)));
  const range = (r) => `${friendly(r[0])}–${friendly(r[1])}`;
  const mdy = (iso, opts) => new Date(iso + "T12:00:00").toLocaleDateString("en-US", opts || { month: "short", day: "numeric" });

  const strat = (id) => SHOWN.find((s) => s.strategy === id);

  // ---------- show-the-math ----------
  // Renders the `math` trace every calculator emits (route + rows). The UI
  // formats only — every value here came from a calculator run; nothing is
  // recomputed in the browser.
  function fmtMathVal(v, fmt) {
    if (fmt === "money") return exact(v);
    if (fmt === "money_range") return `${exact(v[0])} – ${exact(v[1])}`;
    if (fmt === "pct") return (Math.round(v * 1000) / 10) + "%";
    return String(v);
  }

  function mathRowsHtml(m) {
    const rows = m.rows.map((r) =>
      `<div class="mx-row"><span class="mx-label">${r.label}</span><span class="mx-val">${fmtMathVal(r.value, r.fmt)}</span></div>`
    ).join("");
    return `<div class="mx-route">${m.route}</div><div class="mx-rows">${rows}</div>` +
      `<div class="mx-src">Computed from your 2025 return by the calculators — never estimated in conversation.</div>`;
  }

  function mathHtml(s) {
    if (!s || !s.math) return "";
    return `<details class="math-details"><summary>How we got this number</summary>${mathRowsHtml(s.math)}</details>`;
  }

  // ---------- session state ----------
  const plan = SHOWN.map((s) => ({
    id: s.strategy, label: s.label, range: s.range, action: s.action_amount,
    deadline: s.deadline, door: s.door, status: "open", note: "",
  }));
  const learned = {};
  let wrapped = false;

  // ---------- hub rendering ----------
  const ICONS = { "s-corp-election": "🏢", "retirement-optimization": "🏦", "quarterly-estimates": "🗓️", "deduction-optimization": "🧾", "hire-your-kid": "🧒", "asset-depreciation": "🖥️" };
  // Strategy naming guideline: ONE customer-facing name per strategy —
  // verb-led, benefit-first, plain words, 2-4 words, no jargon (jargon lives
  // in the body/deep-dive, once, translated). Same string on the hub card,
  // chat plan cards, chips, and the receipt.
  const SHORT = { "s-corp-election": "Cut self-employment tax", "retirement-optimization": "Save for retirement", "quarterly-estimates": "Stop the penalty", "deduction-optimization": "Find missed deductions", "hire-your-kid": "Pay your kids", "asset-depreciation": "Time a big purchase" };

  function rowValue(p) {
    if (p.status === "accepted") return p.id === "quarterly-estimates" && p.action ? `${exact(p.action)} · ${mdy(p.deadline)}` : "Added to plan";
    if (p.id === "quarterly-estimates") return `Avoid ${exact(CUST.penalty)} penalty`;
    if (p.id === "deduction-optimization") return "Check amount";
    if (p.id === "retirement-optimization") return `Up to ${friendly(p.range[1])}`;
    return p.range ? `~${range(p.range)}` : "Check amount";
  }

  function renderHub() {
    $("cust-first").textContent = CUST.first_name;
    $("return-balance").textContent = `${exact(CUST.balance_due)} total taxes due`;
    $("filed-date").textContent = mdy(CUST.filed_date, { month: "numeric", day: "2-digit", year: "2-digit" });
    $("fed-due").textContent = `${exact(CUST.balance_due)} due`;

    const sized = plan.filter((p) => p.range);
    const projected = sized.reduce((t, p) => t + (p.range[0] + p.range[1]) / 2, 0);
    $("proj-savings").textContent = "~" + friendly(projected);

    // Headline breakdown: midpoints of each move's calculator range, summed.
    // Presentation-only arithmetic — the ranges themselves are calculator output.
    const projMath = $("proj-math"), projHow = $("proj-how");
    if (projMath && projHow && sized.length) {
      const rowsH = sized.map((p) =>
        `<div class="mx-row"><span class="mx-label">${SHORT[p.id] || p.label} (midpoint of ${exact(p.range[0])}–${exact(p.range[1])})</span><span class="mx-val">${exact((p.range[0] + p.range[1]) / 2)}</span></div>`
      ).join("") +
        `<div class="mx-row"><span class="mx-label"><strong>Sum of midpoints</strong></span><span class="mx-val">~${friendly(projected)}</span></div>`;
      projMath.innerHTML = `<div class="mx-route">Midpoint of each plan move's calculator range, summed. Gated moves (no range yet, by design) aren't counted.</div><div class="mx-rows">${rowsH}</div>`;
      projHow.hidden = false;
    }

    const rows = $("plan-rows");
    rows.innerHTML = "";
    plan.forEach((p) => {
      const s = strat(p.id);
      const item = document.createElement("div");
      item.className = "plan-item";
      const wrap = document.createElement("div");
      wrap.className = "plan-row-wrap";
      const btn = document.createElement("button");
      btn.className = "plan-row";
      btn.type = "button";
      const status = p.status === "accepted" ? '<span class="pr-status accepted">ACCEPTED</span>'
        : p.status === "skipped" ? '<span class="pr-status skipped">ON THE TABLE</span>' : "";
      btn.innerHTML = `<span class="pr-left"><span class="pr-ico">${ICONS[p.id] || "•"}</span>${SHORT[p.id] || p.label}</span>
        <span class="pr-right">${status}${rowValue(p)}</span>`;
      btn.addEventListener("click", () => {
        openRail();
        addUser(SHORT[p.id] || p.label);
        deepDive(p.id);
      });
      wrap.appendChild(btn);
      if (s && s.math) {
        const how = document.createElement("button");
        how.className = "pr-how";
        how.type = "button";
        how.title = "How we got this number";
        how.setAttribute("aria-label", `How we got the ${SHORT[p.id] || p.label} number`);
        how.textContent = "ⓘ";
        const panel = document.createElement("div");
        panel.className = "plan-math";
        panel.hidden = true;
        panel.innerHTML = mathRowsHtml(s.math);
        how.addEventListener("click", (e) => { e.stopPropagation(); panel.hidden = !panel.hidden; });
        wrap.appendChild(how);
        item.appendChild(wrap);
        item.appendChild(panel);
      } else {
        item.appendChild(wrap);
      }
      rows.appendChild(item);
    });
  }

  $("return-toggle").addEventListener("click", () => {
    const t = $("return-toggle");
    const open = t.getAttribute("aria-expanded") === "true";
    t.setAttribute("aria-expanded", String(!open));
    $("return-body").classList.toggle("collapsed", open);
  });

  // ---------- chat primitives ----------
  function scrollDown() { scroller.scrollTop = scroller.scrollHeight; }

  function md(text) {
    return text.split("\n\n").map((p) =>
      "<p>" + p.replace(/&/g, "&amp;").replace(/</g, "&lt;")
        .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
        .replace(/\n/g, "<br>") + "</p>"
    ).join("");
  }

  function addUser(text) {
    const el = document.createElement("div");
    el.className = "msg-user";
    el.textContent = text;
    log.appendChild(el);
    scrollDown();
  }

  let queue = Promise.resolve();
  function addAgent(text, delay, extraHtml) {
    queue = queue.then(() => new Promise((done) => {
      const t = document.createElement("div");
      t.className = "msg-agent";
      t.innerHTML = '<span class="typing"><i></i><i></i><i></i></span>';
      log.appendChild(t);
      scrollDown();
      setTimeout(() => {
        t.innerHTML = md(text) + (extraHtml || "");
        scrollDown();
        done();
      }, delay || 650);
    }));
    return queue;
  }

  function setChips(items) {
    queue = queue.then(() => {
      chipsEl.innerHTML = "";
      (items || []).forEach(([label, fn]) => {
        const b = document.createElement("button");
        b.className = "chip";
        b.type = "button";
        b.textContent = label;
        b.addEventListener("click", () => { addUser(label); chipsEl.innerHTML = ""; fn(); });
        chipsEl.appendChild(b);
      });
      scrollDown();
    });
  }

  function setStatus(id, status, note) {
    const p = plan.find((x) => x.id === id);
    if (p) { p.status = status; if (note) p.note = note; renderHub(); }
    maybeWrap();
  }

  // ---------- four-slot turn engine + widget registry ----------
  // Every framework response is a TURN: status pill → one widget → 2–4 spoken
  // sentences → chips ("Show, then ask"). Widgets come only from this
  // registry — the script fills them, never invents layout — and every $
  // inside one is calculator output (window.AOS_DATA), formatted here only.
  // Visual spec: Figma Always-On-Savings 10368-25801 (turn cards) and
  // 10404-29099 (intro worked example).
  function esc(s) { return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;"); }

  function addTurn(t) {
    queue = queue.then(() => new Promise((done) => {
      const el = document.createElement("div");
      el.className = "turn";
      el.innerHTML = '<span class="typing"><i></i><i></i><i></i></span>';
      log.appendChild(el);
      scrollDown();
      setTimeout(() => {
        let h = "";
        if (t.status) h += `<button class="turn-status" type="button" tabindex="-1">${esc(t.status)} <span class="ts-chev">⌄</span></button>`;
        if (t.preVoice) h += md(t.preVoice);
        if (t.widget) h += t.widget;
        if (t.voice) h += md(t.voice);
        el.innerHTML = h;
        const mx = el.querySelector(".w-math");
        if (mx) el.querySelectorAll("[data-mx-toggle]").forEach((b) => {
          b.addEventListener("click", () => { mx.hidden = !mx.hidden; scrollDown(); });
        });
        if (t.wire) t.wire(el);
        scrollDown();
        done();
      }, t.delay || 700);
    }));
    if (t.chips) setChips(t.chips);
    return queue;
  }

  const W = {
    contextChips: (items) =>
      `<div class="w w-ctx">${items.map((c) => `<span class="ctx-chip">${esc(c)}</span>`).join("")}</div>`,

    hero: (o) => {
      const bits = [];
      if (o.sub) bits.push(esc(o.sub));
      if (o.math || (o.mathCustom && o.mathToggle)) bits.push(`<button class="wh-how" type="button" data-mx-toggle>${esc(o.mathLabel || "see the math")} ⌄</button>`);
      return `<div class="w w-hero"><div class="wh-label">${esc(o.label)}</div>` +
        `<div class="wh-amt">${esc(o.amt)}</div>` +
        (o.badge ? `<span class="wh-badge">${esc(o.badge)}</span>` : "") +
        (bits.length ? `<div class="wh-sub">${bits.join(" · ")}</div>` : "") +
        (o.mathCustom ? `<div class="w-math"${o.mathToggle ? " hidden" : ""}>${o.mathCustom}</div>` :
          (o.math ? `<div class="w-math"${o.mathOpen ? "" : " hidden"}>${mathRowsHtml(o.math)}</div>` : "")) +
        `</div>`;
    },

    confidence: (o) =>
      `<div class="w w-conf"><div class="wc-label">HOW SURE AM I?</div>` +
      `<div class="wc-bar"><span style="width:${Math.max(4, Math.min(100, Math.round(o.pct * 100)))}%"></span></div>` +
      `<div class="wc-row locked"><span class="wc-amt">✓ ${esc(o.lockedAmt)} — 100% sure, from your return</span><span class="wc-sub">${esc(o.lockedSub)}</span></div>` +
      `<div class="wc-row pot"><span class="wc-amt">◌ ${esc(o.potAmt)} — depends on you</span><span class="wc-sub">${esc(o.potSub)}</span></div></div>`,

    question: (o) =>
      `<div class="w w-q"><div class="wq-label">${esc(o.n)} OF ${esc(o.of)}${o.unlocks ? " · UNLOCKS " + esc(o.unlocks) : ""}</div>` +
      `<div class="wq-q">${esc(o.q)}</div>` +
      (o.opts ? `<div class="wq-chips">${o.opts.map((l, i) => `<button type="button" class="chip wq-chip" data-i="${i}">${esc(l)}</button>`).join("")}</div>` : "") +
      (o.skip ? `<button type="button" class="wq-skip-btn">${esc(o.skip)}</button>` : "") + `</div>`,

    compare: (o) =>
      `<div class="w w-compare"><div class="wcmp-cols">` +
      `<div class="wcmp-col"><div class="wcmp-k">${esc(o.beforeLabel)}</div><div class="wcmp-v">${esc(o.before)}</div><div class="wcmp-s">${esc(o.beforeSub || o.unit || "")}</div></div>` +
      `<div class="wcmp-col after"><div class="wcmp-k">${esc(o.afterLabel)}</div><div class="wcmp-v">${esc(o.after)}</div><div class="wcmp-s">${esc(o.afterSub || o.unit || "")}</div></div>` +
      `</div><div class="wcmp-note">${esc(o.note)}</div>` +
      (o.math ? `<div class="w-math" hidden>${mathRowsHtml(o.math)}</div>` : "") + `</div>`,

    diagram: (o) =>
      `<div class="w w-diagram"><div class="wd-row">` +
      o.inputs.map((n) => `<span class="wd-n">${esc(n)}</span>`).join('<span class="wd-op">+</span>') +
      `</div><span class="wd-op">↓</span><div class="wd-row"><span class="wd-n sum">${esc(o.sum)}</span></div></div>`,

    moveList: (shown) => {
      let n = 0;
      return `<div class="w w-moves">` + shown.map((s) => {
        const sure = s.range_kind === "penalty_avoided"; // calculator-flagged certainty — applies to ANY strategy the engine marks certain
        const val = s.action_amount ? `${friendly(s.action_amount)} due ${mdy(s.deadline)} — kills the penalty for good`
          : s.range ? `~${range(s.range)}${s.strategy === "s-corp-election" ? "/yr" : " this year"}`
          : "No number until you connect — by design";
        return `<div class="wm-row">` +
          `<span class="wm-rank">${++n}</span>` +
          `<span class="wm-body"><span class="wm-name">${esc(SHORT[s.strategy] || s.label)}</span>` +
          `<span class="wm-val">${esc(val)}</span></span>` +
          (sure ? '<span class="wm-tag sure">100% SURE</span>' : "") + `</div>`;
      }).join("") + `</div>`;
    },

    moveListLean: (shown) => {
      const M = {
        "s-corp-election": (x) => ({
          title: SHORT["s-corp-election"],
          amount: "~" + range(x.range) + "/yr",
          body: `An S-Corp splits your income so part of it skips the 15.3% self-employment tax. On your ${compact(CUST.net_profit)} profit, that keeps about ${range(x.range)} a year.`,
          eff: "EXPERT CALL",
        }),
        "retirement-optimization": (x) => ({
          title: SHORT["retirement-optimization"],
          amount: "Up to " + friendly(x.range[1]) + " this year",
          body: `A Solo 401(k) or SEP shelters income before it's taxed — you have room for ~${friendly(x.detail.headroom.sep_max)} by Dec 31. Cuts this year's tax by up to ${friendly(x.range[1])}, deferred not erased.`,
          eff: "~20 MIN",
        }),
        "quarterly-estimates": (x) => ({
          title: SHORT["quarterly-estimates"],
          amount: friendly(x.action_amount) + " due " + mdy(x.deadline),
          body: `Last April cost you ${exact(CUST.penalty)} in penalty. Paying ${friendly(x.action_amount)} by ${mdy(x.deadline)} keeps that from repeating.`,
          eff: "5 MIN",
        }),
        "deduction-optimization": (x) => ({
          title: SHORT["deduction-optimization"],
          amount: "Sized once you connect your bank",
          body: `Your expenses run ~${Math.round(x.detail.expense_ratio * 100)}% of revenue; similar businesses run ~${Math.round(x.detail.benchmark_ratio * 100)}%. Connecting your bank finds what's missing.`,
          eff: "2 MIN",
        }),
        "hire-your-kid": (x) => ({
          title: SHORT["hire-your-kid"],
          amount: "~" + range(x.range) + "/yr",
          body: `Wages you pay your kids shift income from your bracket to their 0% rate. That's worth about ${range(x.range)} a year.`,
          eff: "EXPERT CALL",
        }),
      };
      let n = 0;
      return `<div class="w w-moves">` + shown.map((x) => {
        const m = (M[x.strategy] || (() => ({ title: SHORT[x.strategy] || x.label, amount: x.range ? "~" + range(x.range) : "", body: "", eff: "" })))(x);
        return `<button type="button" class="wm-card" data-strategy="${esc(x.strategy)}">` +
          `<span class="wm-rank">${++n}</span>` +
          `<span class="wm-body"><span class="wm-name">${esc(m.title)}</span>` +
          `<span class="wm-amt">${esc(m.amount)}</span>` +
          `<span class="wm-val">${esc(m.body)}</span></span>` +
          (m.eff ? `<span class="wm-eff">${esc(m.eff)}</span>` : "") +
          `<span class="wm-chev">›</span></button>`;
      }).join("") + `</div>`;
    },

    moveCard: (o) =>
      `<div class="w w-move"><div class="wmv-k">${esc(o.k)}</div><div class="wmv-h">${esc(o.h)}</div><div class="wmv-s">${esc(o.s)}</div></div>`,
  };

  // ---------- five-block intro (Recognition → Value → Confidence → 3 Qs → Paths) ----------
  // Content framework: Figma 10400-27438. All $ figures below come from
  // D.benchmark / D.analysis (calculator output). Known deviations from the
  // canonical worked example, both flagged in the build notes: no calculator
  // emits the "+$ vs last year" delta or a return-visible unclaimed-deduction
  // figure, so the hero badge is omitted and "locked in" = the underpayment
  // penalty alone.
  const PLAN_YEAR = Number((D.as_of || "2026").slice(0, 4));

  function introContextChips() {
    const items = [];
    const biz = (CUST.business || "Your business").replace(/^Independent\s+/i, "").replace(/\s*\(.*?\)/g, "").trim();
    items.push(`${biz.charAt(0).toUpperCase() + biz.slice(1)} · sole prop`);
    items.push(`${compact(CUST.net_profit)} net profit`);
    const april = [];
    if (CUST.balance_due > 0) april.push(`${exact(CUST.balance_due)} due`);
    if (CUST.penalty > 0) april.push(`${exact(CUST.penalty)} penalty`);
    items.push(april.length ? `April: ${april.join(" + ")}` : "April: no balance due");
    return items;
  }

  // Hardik's five-question onboarding framework (Slack 7/9), surfaced
  // conditionally by customer situation — max 3 asked per session (agent
  // spec G9). Q1 + Q2 always; the third slot is trigger-driven:
  // kids (if hire-your-kid lacks ages) → purchases (if deductions fired,
  // §179 folded into deduction opt per charter) → big-changes catch-all.
  function introQuestions() {
    const qs = [
      {
        unlocks: "QUARTERLY + S-CORP SIZING",
        q: `How's ${PLAN_YEAR} income looking, compared to last year's ${compact(CUST.net_profit)}?`,
        skip: "Skip — I'll use last year's numbers",
        opts: [["Higher", "higher"], ["About the same", "same"], ["Lower", "lower"]],
        save: (v) => { learned.income_trajectory = v; },
      },
      {
        unlocks: "HOW I RANK YOUR MOVES",
        q: "What matters more right now — cash on hand day to day, or maximizing what you keep long-term?",
        skip: "Skip — I'll balance both",
        opts: [["Cash on hand", "cash_flow"], ["Long-term keep", "savings"], ["A bit of both", "both"]],
        save: (v) => { learned.optimize_for = v; },
      },
    ];
    const analysis = D.analysis || {};
    const needsCtx = (analysis.needs_context || []).map((s) => s.strategy || s);
    const gaps = analysis.onboarding_gaps || [];
    const shownIds = SHOWN.map((s) => s.strategy);
    if (needsCtx.includes("hire-your-kid")) {
      qs.push({
        unlocks: "HIRE-YOUR-KID SIZING",
        q: "Do you have kids at home? If so, what ages?",
        skip: "Skip this one",
        opts: [["Yes, 7–17", "kids_7_17"], ["Yes, younger", "kids_under_7"], ["Yes, 18+", "kids_18_plus"], ["No kids", "none"]],
        save: (v) => { learned.household_kids = v; },
      });
    } else if (shownIds.includes("deduction-optimization") && gaps.includes("planned_purchases")) {
      qs.push({
        unlocks: "EQUIPMENT WRITE-OFF TIMING",
        q: "Planning any big equipment or vehicle purchases this year?",
        skip: "Skip this one",
        opts: [["Yes, something big", "yes"], ["Maybe", "maybe"], ["No", "no"]],
        save: (v) => { learned.planned_purchases = v; },
      });
    } else {
      qs.push({
        unlocks: "ANYTHING THE RETURN CAN'T SEE",
        q: "Anything big changing this year — getting married, a new kid, switching health coverage?",
        skip: "Skip this one",
        opts: [["Getting married", "marriage"], ["New kid", "new_kid"], ["Coverage switch", "coverage"], ["Nothing big", "none"]],
        save: (v) => { learned.big_changes = v; },
      });
    }
    return qs.slice(0, 3);
  }

  function introQuestionsLean() {
    return [
      {
        unlocks: null,
        q: `How's your ${PLAN_YEAR} income looking compared to last year's income of ${exact(CUST.net_profit)}?`,
        skip: "Skip — I'll use last year's numbers",
        opts: [["Higher", "higher"], ["About the same", "same"], ["Lower", "lower"]],
        save: (v) => { learned.income_trajectory = v; },
      },
      {
        unlocks: null,
        q: "Are you putting money into retirement accounts?",
        skip: "Skip this one",
        opts: [["Yes, an IRA", "ira"], ["An old 401(k)", "old_401k"], ["No, nothing yet", "none"], ["Not sure", "unsure"]],
        save: (v) => { learned.retirement_existing = v; },
      },
      {
        unlocks: null,
        q: "Where does your health coverage come from?",
        skip: "Skip this one",
        opts: [["Marketplace", "marketplace"], ["Spouse's plan", "spouse"], ["Elsewhere", "elsewhere"]],
        save: (v) => { learned.health_coverage = v; },
      },
    ];
  }

  function askIntroQ(qs, i) {
    if (i >= qs.length) return finishIntro();
    const q = qs[i];
    addTurn({
      widget: W.question({ n: i + 1, of: qs.length, unlocks: q.unlocks, q: q.q, opts: q.opts.map((o) => o[0]), skip: q.skip }),
      delay: i === 0 ? 500 : 800,
      wire: (el) => {
        const card = el.querySelector(".w-q");
        const done = (val, btn) => {
          if (!card || card.classList.contains("answered")) return;
          card.classList.add("answered");
          card.querySelectorAll("button").forEach((b) => { b.disabled = true; });
          if (btn) btn.classList.add("selected");
          if (val !== null) q.save(val);
          askIntroQ(qs, i + 1);
        };
        el.querySelectorAll(".wq-chip").forEach((btn) =>
          btn.addEventListener("click", () => done(q.opts[Number(btn.dataset.i)][1], btn)));
        const sk = el.querySelector(".wq-skip-btn");
        if (sk) sk.addEventListener("click", () => done(null, sk));
      },
    });
  }

  function introPlanTurn(liveChipLabels) {
    queue = queue.then(() => { $("analysis-label").hidden = false; renderHub(); revealPlanCard(); });
    const lean = INTRO_VARIANT === "lean";
    addTurn({
      status: "Plan updated on your tax hub",
      preVoice: lean ? `Your plan — ${SHOWN.length} moves, ranked by the biggest savings first. Tap one to dig in.` : null,
      widget: lean ? W.moveListLean(SHOWN) : W.moveList(SHOWN),
      voice: lean ? null
        : "That's your plan — biggest dollars first. The Q3 payment is the sure thing; it locks in when you pay. Every number comes from your return. Where do you want to start?",
      delay: 1300,
      chips: lean ? null : (liveChipLabels ? null : planChips()),
      wire: lean ? (el) => {
        el.querySelectorAll(".wm-card").forEach((card) => card.addEventListener("click", () => {
          const id = card.dataset.strategy;
          if (LIVE) { liveAsk(`Tell me more about ${SHORT[id] || id}`); return; }
          addUser(SHORT[id] || id); // visualize the choice in the transcript
          deepDive(id);
        }));
      } : null,
    });
    if (liveChipLabels) queue = queue.then(() => setLiveChips(liveChipLabels));
  }

  async function finishIntro() {
    if (!LIVE) { introPlanTurn(null); return; }
    // Live mode: hand the collected answers to the real agent in one message,
    // render its reply, then show the same calculator-seeded plan turn.
    const parts = [];
    if (learned.income_trajectory) parts.push(`income vs last year: ${learned.income_trajectory}`);
    if (learned.retirement_existing) parts.push(`already saving for retirement: ${learned.retirement_existing}`);
    if (learned.health_coverage) parts.push(`health coverage: ${learned.health_coverage}`);
    const bubble = addLiveBubble();
    try {
      const data = await sendLiveMessage(
        `My onboarding answers — ${parts.length ? parts.join("; ") : "I skipped all three questions, use the return as filed"}.`);
      fillLiveBubble(bubble, data.reply);
    } catch (e) {
      fillLiveBubble(bubble, `Sorry — I couldn't reach the live agent (${e.message}).`);
    }
    liveOnboardPending = false;
    await refreshHubFromPlan();
    introPlanTurn(SHOWN.map((s) => `Tell me more about ${SHORT[s.strategy] || s.label}`));
  }

  // Onboarding core = confidence split + the three questions + plan reveal.
  // Shared by both entries: the side-rail intro (after blocks 0–1) and the
  // full-screen omni welcome ("Build my savings plan" chip).
  function runOnboardingCore() {
    if (INTRO_VARIANT === "lean") { askIntroQ(introQuestionsLean(), 0); return; }
    const b = D.benchmark;
    const locked = b.left_on_table_last_year || 0;
    const potential = Math.max(0, b.estimate - locked);
    if (locked > 0) {
      addTurn({
        widget: W.confidence({
          pct: locked / b.estimate,
          lockedAmt: exact(locked),
          lockedSub: `April's ${exact(locked)} penalty won't repeat — as long as each quarterly payment lands on time. You confirm each one; I track them.`,
          potAmt: `Up to ~${friendly(potential)} more`,
          potSub: `Sized by three quick answers about next year. That's where the S-Corp, retirement, and deduction moves live.`,
        }),
        voice: `The first part is already yours — I found it sitting in the return. The bigger part depends on a few things only you know. Three quick taps and I'll show you the full plan.\n\nYou can follow my lead — or ask me any tax question, anytime.`,
        delay: 1000,
      });
    } else {
      addTurn({
        voice: `You stayed penalty-free last year — the whole number is upside. It depends on a few things only you know, so: three quick taps and I'll show you the full plan.\n\nYou can follow my lead — or ask me any tax question, anytime.`,
        delay: 900,
      });
    }
    askIntroQ(introQuestions(), 0);
  }

  // Full-screen entry (left-nav "Year-round savings") — the customer skipped
  // the hero card, so welcome first and guide progressively: greeting →
  // recognition chips → the savings card with detail → opt-in to onboarding.
  function runOmniWelcome() {
    introStarted = true;
    const b = D.benchmark;
    if (!b) { if (LIVE) startLiveSession(); else start(); return; }
    if (LIVE) { liveOnboardPending = true; liveOnboardTurns = 0; }
    const cta = $("hero-cta");
    if (cta) cta.textContent = "Continue in chat →"; // stays live — reopens the rail
    queue = queue.then(() => new Promise((done) => {
      const el = document.createElement("div");
      el.className = "omni-welcome";
      el.innerHTML =
        '<span class="ow-spark"><svg viewBox="0 0 28 28" width="30" height="30"><path d="M14 2l2.4 8.2L25 12l-8.6 1.8L14 22l-2.4-8.2L3 12l8.6-1.8z" fill="#236cff"/><circle cx="21.5" cy="5.5" r="2" fill="#236cff"/></svg></span>' +
        `<div class="ow-hi">Hi, ${esc(CUST.first_name)}</div>` +
        `<div class="ow-sub">I'm your year-round savings agent. I've already read your 2025 return — nothing to upload, nothing to explain. Here's what I'm working from:</div>`;
      log.appendChild(el);
      scrollDown();
      done();
    }));
    addTurn({ widget: W.contextChips(introContextChips()), delay: 400 });
    // The gateway card — same anatomy as the Tax home savings card
    // (title, amount, badge, illustration, blurb, estimate link), so both
    // entry points share one mental model. The CTA lives OUTSIDE the card,
    // right after the welcome voice.
    const lean = INTRO_VARIANT === "lean";
    const gateHtml =
      `<div class="w w-hero-gate">` +
      `<div class="hero-title">${PLAN_YEAR} projected savings</div>` +
      `<div class="hero-amt">~${esc(friendly(b.estimate))}</div>` +
      `<div class="whg-illo"><img src="hero-illustration.png" alt=""></div>` +
      `<p class="hero-blurb">${lean
        ? `Discover how to maximize your savings for next year with a customized tax savings plan.`
        : (b.left_on_table_last_year > 0
          ? `Last year you paid <strong>${exact(b.left_on_table_last_year)}</strong> in penalties — money left on the table. Let's maximize this year's return.`
          : `You stayed penalty-free last year. Let's go further and capture the savings still on the table.`)}</p>` +
      (lean ? "" : `<button type="button" class="hero-how" data-mx-toggle>How we got this estimate</button>` +
        `<div class="w-math" hidden>${mathRowsHtml(b.math)}</div>`) +
      `</div>`;
    addTurn({
      widget: gateHtml,
      voice: "Part of that number is already certain — the rest takes three quick taps.\n\nFollow my lead, or ask your own tax questions — the box below is always open.",
      delay: 1000,
    });
    addTurn({
      widget: `<div class="omni-start"><button type="button" class="chip omni-start-btn">Start my savings plan</button></div>`,
      delay: 500,
      wire: (el) => {
        const btn = el.querySelector(".omni-start-btn");
        if (btn) btn.addEventListener("click", () => {
          if (btn.disabled) return;
          btn.disabled = true;
          runOnboardingCore();
        });
      },
    });
  }

  function runIntroLean() {
    const b = D.benchmark;
    const rowsH = b.math.rows.map((r) =>
      `<div class="mx-row"><span class="mx-label">${r.label}</span><span class="mx-val">${fmtMathVal(r.value, r.fmt)}</span></div>`).join("");
    addTurn({
      preVoice: `Hi ${CUST.first_name}. From your 2025 return, here's what next year could look like.`,
      widget: W.hero({
        label: `${PLAN_YEAR} PROJECTED SAVINGS`,
        amt: "~" + friendly(b.estimate),
        mathCustom: `<div class="lean-math-blurb">Solo businesses like yours typically save 3–6% of net profit in year one. Answer a few questions and this becomes your personalized number.</div>` +
          `<div class="mx-rows">${rowsH}</div>`,
        mathToggle: true,
        mathLabel: "How we got this number",
      }),
      voice: "Answer three quick questions so I can tailor it to you and recommend specific strategies.",
      delay: 700,
    });
    askIntroQ(introQuestionsLean(), 0);
  }

  function runIntro() {
    if (INTRO_VARIANT === "lean") return runIntroLean();
    const b = D.benchmark;
    // Block 0 · Recognition — prove context in 3 seconds, no value claim yet.
    addTurn({
      status: "Read your 2025 return · just now",
      preVoice: `Hey ${CUST.first_name}. I've already read your 2025 return, so there's nothing to upload and nothing to explain — I'm starting caught up. Here's what I'm working from:`,
      widget: W.contextChips(introContextChips()),
      voice: `The good news: next April doesn't have to look like this one. I ran your return against the strategies that work for businesses like yours, and here's where you stand.`,
      delay: 600,
    });
    // Block 1 · Value — the number, attributed so it reads as computed.
    addTurn({
      widget: W.hero({
        label: `${PLAN_YEAR} PROJECTED SAVINGS`,
        amt: "~" + friendly(b.estimate),
        sub: `Computed from your return · ${SHOWN.length} strategies apply`,
        math: b.math,
      }),
      delay: 1100,
    });
    // Blocks 2–3 · confidence split + questions (shared with omni entry).
    runOnboardingCore();
  }

  // ---------- receipt / wrap ----------
  function receiptHtml() {
    const accepted = plan.filter((p) => p.status === "accepted");
    const open = plan.filter((p) => p.status !== "accepted");
    let h = '<div class="rc-title">Your receipt</div><ul>';
    accepted.forEach((p) => { h += `<li>✅ ${SHORT[p.id]} — ${p.note || rowValue(p)}</li>`; });
    open.forEach((p) => { h += `<li>◽ On the table: ${SHORT[p.id]}${p.range ? ` (~${range(p.range)}${p.id === "s-corp-election" ? "/yr" : ""})` : ""}</li>`; });
    h += "</ul>";
    return h;
  }

  function showReceipt() {
    queue = queue.then(() => {
      const el = document.createElement("div");
      el.className = "msg-receipt";
      el.innerHTML = receiptHtml();
      log.appendChild(el);
      scrollDown();
    });
    addAgent("I'll check back before your **Q4 payment in January** — sooner if anything on your plan gets time-sensitive. Nothing here is locked; every move stays on the table.");
  }

  function maybeWrap() {
    if (wrapped || plan.some((p) => p.status === "open")) return;
    wrapped = true;
    addAgent("That's every move handled. Here's where you land:");
    showReceipt();
    setChips([["View summary", showReceipt]]);
  }

  $("view-summary").addEventListener("click", showReceipt);

  // ---------- live mode (backend-powered chat, additive) ----------
  // When ui/server.py is running, the chat rail is driven by the real
  // `claude` CLI (Detect Agent persona + strategy skills + calculators) —
  // see ui/server.py for the API contract. Everything above/below this
  // block is the original scripted fallback and is untouched; it still
  // runs standalone (e.g. opening index.html via file://) with no backend.
  let LIVE = false;
  let CLIENT_SESSION_ID = null;

  // ---------- onboarding entry state (hero → plan) ----------
  // The plan card starts in its hero/estimate state; the customer begins from
  // its "Secure all savings" CTA, which opens the chat and runs onboarding.
  // Only after onboarding completes does the card reveal the ranked plan.
  // In live mode the agent's turns are free-form, so we reveal after this many
  // user replies (the 2-question onboarding) — presentation-only, no backend.
  let liveOnboardPending = false;
  let liveOnboardTurns = 0;
  const LIVE_ONBOARD_TURNS = 2;
  const summaryRow = () => document.querySelector(".summary-row");

  function revealPlanCard() {
    const hero = $("savings-hero"), planEl = $("savings-plan");
    if (hero) hero.hidden = true;
    if (planEl) planEl.hidden = false;
    // summary-row control stays hidden — it reads as a user bubble in the
    // transcript; the receipt lives on the "View summary" chip instead.
  }

  function renderHero() {
    const b = D.benchmark;
    if (!b) { revealPlanCard(); return false; }  // older data w/o benchmark → skip hero
    const amt = $("hero-amt");
    if (amt) amt.textContent = "~" + friendly(b.estimate);
    const blurb = $("hero-blurb");
    if (blurb) {
      blurb.innerHTML = b.left_on_table_last_year > 0
        ? `Last year you paid <strong>${exact(b.left_on_table_last_year)}</strong> in penalties — money left on the table. Let's maximize this year's return.`
        : `You stayed penalty-free last year. Let's go further and capture the savings still on the table.`;
    }
    const heroMath = $("hero-math");
    if (heroMath && b.math) heroMath.innerHTML = mathRowsHtml(b.math);
    if (INTRO_VARIANT === "lean") {
      const badge = $("hero-badge"); if (badge) badge.hidden = true;
      if (blurb) blurb.textContent = "Discover how to maximize your savings for next year with a customized tax savings plan.";
      const how = $("hero-how"); if (how) how.hidden = true;
    }
    return true;
  }

  // ---------- chat rail: collapse / expand / omni (full-screen) ----------
  // The rail starts closed (.app.rail-closed in the markup). The hero CTA and
  // the "Savings agent" nav item open it; the X closes it (conversation state
  // is preserved — the log is never cleared); the expand button toggles omni.
  const appEl = document.querySelector(".app");
  let introStarted = false; // the intro runs at most once per page load

  const EXPAND_SVG = '<svg viewBox="0 0 20 20" width="19" height="19"><path d="M11.5 3.5h5v5M8.5 16.5h-5v-5M16.5 3.5l-5.8 5.8M3.5 16.5l5.8-5.8" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg>';
  const COLLAPSE_SVG = '<svg viewBox="0 0 20 20" width="19" height="19"><path d="M16.5 8.5h-5v-5M3.5 11.5h5v5M17 3l-5.5 5.5M3 17l5.5-5.5" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg>';

  function openRail() { if (appEl) appEl.classList.remove("rail-closed"); }
  function closeRail() { if (appEl) appEl.classList.add("rail-closed"); }

  function setOmni(on) {
    if (!appEl) return;
    appEl.classList.toggle("omni", on);
    if (on) appEl.classList.remove("rail-closed"); // exiting omni lands on the open side rail
    const ex = $("chat-expand");
    if (ex) { ex.setAttribute("aria-label", on ? "Collapse" : "Expand"); ex.innerHTML = on ? COLLAPSE_SVG : EXPAND_SVG; }
    const agentNav = $("nav-savings-agent"), homeNav = $("nav-tax-home");
    if (agentNav) agentNav.classList.toggle("active", on);
    if (homeNav) homeNav.classList.toggle("active", !on);
    scrollDown();
  }

  function wireRail() {
    const ex = $("chat-expand");
    if (ex) ex.addEventListener("click", () => setOmni(!appEl.classList.contains("omni")));
    const x = $("chat-close");
    if (x) x.addEventListener("click", () => { setOmni(false); closeRail(); });
    const agentNav = $("nav-savings-agent");
    const homeNav = $("nav-tax-home");
    if (homeNav) homeNav.addEventListener("click", (e) => {
      e.preventDefault();
      if (appEl.classList.contains("omni")) setOmni(false); // back to hub, rail stays open with the convo
    });
    if (agentNav) agentNav.addEventListener("click", (e) => {
      e.preventDefault();
      setOmni(true);
      // Direct nav entry gets the dedicated omni welcome (progressive
      // onboarding); the hero-card path keeps the five-block intro.
      if (!introStarted) runOmniWelcome();
    });
  }

  function startConversationOnce() {
    if (introStarted) return; // reopening the rail never restarts the intro
    introStarted = true;
    addUser("Start my savings plan"); // transcript echoes the tax-home button
    const cta = $("hero-cta");
    if (cta) cta.textContent = "Continue in chat →"; // stays live — reopens the rail
    const box = $("chat-text"); if (box) box.focus({ preventScroll: true });
    // Five-block intro (framework) runs deterministically in BOTH modes —
    // recognition, hero, and the confidence split are pure calculator output.
    // In live mode the collected answers are handed to the real agent at the
    // end (finishIntro); the old direct paths remain for no-benchmark returns.
    if (LIVE) { liveOnboardPending = true; liveOnboardTurns = 0; }
    if (D.benchmark) { runIntro(); return; }
    if (LIVE) startLiveSession(); else start();
  }

  function beginOnboarding() {
    openRail(); // slide the rail in first, then run (or resume) the conversation
    startConversationOnce();
  }

  function wireHero() {
    const cta = $("hero-cta");
    if (cta) cta.addEventListener("click", beginOnboarding);
    const how = $("hero-how"), panel = $("hero-math");
    if (how && panel) how.addEventListener("click", () => { panel.hidden = !panel.hidden; });
  }

  function setModePill(isLive) {
    const pill = $("mode-pill");
    if (!pill) return;
    pill.textContent = isLive ? "Live" : "Demo";
    pill.classList.toggle("mode-live", isLive);
    pill.classList.toggle("mode-demo", !isLive);
  }

  async function checkLiveMode() {
    try {
      const res = await fetch("/api/health", { cache: "no-store" });
      if (!res.ok) return false;
      const data = await res.json();
      return data && data.status === "ok";
    } catch (e) {
      return false; // no server (e.g. file://) — fall back to the scripted demo
    }
  }

  async function liveApiCall(path, body) {
    const res = await fetch(path, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
    let data = null;
    try { data = await res.json(); } catch (e) { /* non-JSON error body, ignore */ }
    if (!res.ok) throw new Error((data && data.error) || `request failed (HTTP ${res.status})`);
    return data;
  }

  function addLiveBubble() {
    const t = document.createElement("div");
    t.className = "msg-agent";
    t.innerHTML = '<span class="typing"><i></i><i></i><i></i></span>';
    log.appendChild(t);
    scrollDown();
    return t;
  }

  function fillLiveBubble(node, text) {
    node.innerHTML = md(text || "");
    scrollDown();
  }

  // Quick-reply chips in live mode are generated from the *real* plan on
  // disk (state/sessions/<id>/savings_plan.json via GET /api/plan/<id>),
  // never scripted — clicking one just fills the input and submits, same
  // as typing it, so the reply always comes from the live agent.
  function liveAsk(text) {
    openRail(); // hub plan rows land in the chat — make sure it's visible
    input.value = text;
    submit();
  }

  function setLiveChips(labels) {
    chipsEl.innerHTML = "";
    labels.forEach((label) => {
      const b = document.createElement("button");
      b.className = "chip";
      b.type = "button";
      b.textContent = label;
      b.addEventListener("click", () => liveAsk(label));
      chipsEl.appendChild(b);
    });
    scrollDown();
  }

  function rowValueServer(s) {
    if (s.status === "accepted") return s.id === "quarterly-estimates" && s.action_amount ? `${exact(s.action_amount)} · ${mdy(s.deadline)}` : "Added to plan";
    if (s.id === "quarterly-estimates") return s.action_amount ? `${exact(s.action_amount)} due ${mdy(s.deadline)}` : "Check amount";
    if (s.id === "deduction-optimization") return "Check amount";
    return s.range ? `~${range(s.range)}` : "Check amount";
  }

  // Adapts the hub's plan-rows UI to state/sessions/<id>/savings_plan.json's
  // `strategies` shape instead of the local scripted `plan` array.
  function renderHubFromServerPlan(planData) {
    const rows = $("plan-rows");
    if (!rows || !planData || !Array.isArray(planData.strategies)) return;
    const strategies = planData.strategies;

    const sized = strategies.filter((s) => s.range);
    if (strategies.length) {
      const projected = sized.reduce((t, s) => t + (s.range[0] + s.range[1]) / 2, 0);
      $("proj-savings").textContent = "~" + friendly(projected);
    }

    rows.innerHTML = "";
    strategies.forEach((s) => {
      const short = SHORT[s.id] || s.label;
      const item = document.createElement("div");
      item.className = "plan-item";
      const wrap = document.createElement("div");
      wrap.className = "plan-row-wrap";
      const btn = document.createElement("button");
      btn.className = "plan-row";
      btn.type = "button";
      const status = s.status === "accepted" ? '<span class="pr-status accepted">ACCEPTED</span>'
        : s.status === "skipped" ? '<span class="pr-status skipped">ON THE TABLE</span>' : "";
      btn.innerHTML = `<span class="pr-left"><span class="pr-ico">${ICONS[s.id] || "•"}</span>${short}</span>
        <span class="pr-right">${status}${rowValueServer(s)}</span>`;
      btn.addEventListener("click", () => liveAsk(`Tell me more about ${short}`));
      wrap.appendChild(btn);
      // Math trace comes from the seeded analysis for this return (same
      // calculators the live agent runs). If a live what-if later moves a
      // range, the trace still explains the seeded computation.
      const seed = strat(s.id);
      if (seed && seed.math) {
        const how = document.createElement("button");
        how.className = "pr-how";
        how.type = "button";
        how.title = "How we got this number";
        how.setAttribute("aria-label", `How we got the ${short} number`);
        how.textContent = "ⓘ";
        const panel = document.createElement("div");
        panel.className = "plan-math";
        panel.hidden = true;
        panel.innerHTML = mathRowsHtml(seed.math);
        how.addEventListener("click", (e) => { e.stopPropagation(); panel.hidden = !panel.hidden; });
        wrap.appendChild(how);
        item.appendChild(wrap);
        item.appendChild(panel);
      } else {
        item.appendChild(wrap);
      }
      rows.appendChild(item);
    });

    setLiveChips(strategies.filter((s) => s.status === "open").map((s) => SHORT[s.id] || s.label));
  }

  async function refreshHubFromPlan() {
    try {
      const res = await fetch(`/api/plan/${encodeURIComponent(CUST.id)}`, { cache: "no-store" });
      if (!res.ok) return; // e.g. 404 before the first plan write — keep showing the seeded hub
      renderHubFromServerPlan(await res.json());
    } catch (e) { /* non-fatal — hub just keeps its last known state */ }
  }

  // Start (or re-start) a live session and remember its id. Returns the
  // server's opening payload so callers can decide whether to render it.
  async function establishSession() {
    const data = await liveApiCall("/api/session/start", { customer: CUST.id, as_of: D.as_of });
    CLIENT_SESSION_ID = data.client_session_id;
    return data;
  }

  async function startLiveSession() {
    const bubble = addLiveBubble();
    try {
      const data = await establishSession();
      fillLiveBubble(bubble, data.reply);
    } catch (e) {
      fillLiveBubble(bubble, `Sorry — I couldn't reach the live agent (${e.message}). Refresh to try again.`);
      const cta = $("hero-cta");
      if (cta) { cta.disabled = false; cta.textContent = "Start my savings plan"; }
      introStarted = false; // the CTA is live again — let it retry the intro
    }
    // Onboarding first — the plan card stays in its hero/estimate state until
    // the customer answers onboarding (see liveSubmit). No reveal yet.
  }

  // Send one chat turn, recovering transparently from a missing session id
  // (boot handshake never completed) or a stale one (server restarted and
  // dropped its in-memory session map) by re-starting once and retrying.
  // The recovery session's opening reply is discarded so the conversation
  // isn't re-hooked mid-stream.
  async function sendLiveMessage(text) {
    if (!CLIENT_SESSION_ID) await establishSession();
    try {
      return await liveApiCall("/api/chat", { client_session_id: CLIENT_SESSION_ID, message: text });
    } catch (e) {
      if (/client_session_id/i.test(e.message)) {
        await establishSession();
        return await liveApiCall("/api/chat", { client_session_id: CLIENT_SESSION_ID, message: text });
      }
      throw e;
    }
  }

  async function liveSubmit(text) {
    addUser(text);
    chipsEl.innerHTML = "";
    const bubble = addLiveBubble();
    try {
      const data = await sendLiveMessage(text);
      fillLiveBubble(bubble, data.reply);
    } catch (e) {
      fillLiveBubble(bubble, `Sorry — that didn't go through (${e.message}). Try again?`);
    }
    if (liveOnboardPending) {
      // Count onboarding answers; reveal the ranked plan once they're in.
      liveOnboardTurns++;
      if (liveOnboardTurns >= LIVE_ONBOARD_TURNS) {
        liveOnboardPending = false;
        $("analysis-label").hidden = false;
        await refreshHubFromPlan();
        revealPlanCard();
      }
      return;
    }
    await refreshHubFromPlan();
  }

  // ---------- onboarding ----------
  function start() {
    const filedClause = CUST.penalty > 0
      ? `, and you paid a **${exact(CUST.penalty)} penalty** in April`
      : (CUST.balance_due > 0
        ? `, and you owed **${exact(CUST.balance_due)}** at filing`
        : `, and your withholding kept you penalty-free`);
    addAgent(`Hi ${CUST.first_name} — based on your return: **${friendly(CUST.net_profit)} business net profit**${filedClause}. Let me build a plan to keep more this year.\n\nFirst — is income tracking higher, lower, or about the same as last year?`, 900);
    setChips([
      ["About the same", () => onboard1("same")],
      ["Higher", () => onboard1("higher")],
      ["Lower", () => onboard1("lower")],
    ]);
  }

  function onboard1(traj) {
    learned.income_trajectory = traj;
    const ack = traj === "same" ? "Got it." : "Got it — I'll keep the numbers tuned to that as it firms up; you can give me a rough figure any time.";
    addAgent(`${ack} One more to tune the plan — health coverage: spouse's plan, marketplace, or none?`);
    setChips([
      ["Marketplace", () => onboard2("marketplace")],
      ["Spouse's plan", () => onboard2("spouse")],
      ["None", () => onboard2("none")],
    ]);
  }

  function onboard2(cov) {
    learned.health_coverage = cov;
    queue = queue.then(() => { $("analysis-label").hidden = false; renderHub(); revealPlanCard(); });
    revealPlan();
  }

  // ---------- plan reveal ----------
  function planMessage() {
    const parts = [`Here's your plan — ${plan.length} moves, biggest first. Every dollar comes from your 2025 return; ranges tighten as you confirm details.`];
    let n = 1;
    SHOWN.forEach((s) => {
      if (s.strategy === "s-corp-election") {
        parts.push(`**${n++} · S-Corp election — save ~${range(s.range)}/yr**\nAt ${friendly(CUST.net_profit)} net, an S-Corp cuts self-employment tax. That's a range off your return; the exact figure is an expert's to set. 2026's window has passed — we'd set you up for 2027.`);
      } else if (s.strategy === "retirement-optimization") {
        const top = s.detail.levels[s.detail.levels.length - 1];
        parts.push(`**${n++} · Retirement — defer up to ${friendly(s.range[1])} this year**\nA SEP could hold ~${friendly(top.contribution)} and knock ~${friendly(s.range[1])} off this year's tax — bigger headline, but you pay it later on withdrawal, not erased. By Dec 31.`);
      } else if (s.strategy === "quarterly-estimates") {
        parts.push(`**${n++} · Q3 payment — ${friendly(s.action_amount)}, due ${mdy(s.deadline)}**\nQ1 and Q2 paid on time. Pay this and April's ${exact(CUST.penalty)} penalty can't return. We can recalculate it for a more cash-optimized number if income shifts.`);
      } else if (s.strategy === "deduction-optimization") {
        const d = s.detail;
        parts.push(`**${n++} · Deductions — worth a look, no number yet**\nYour expenses run ~${Math.round(d.expense_ratio * 100)}% of revenue; ${d.benchmark_label.toLowerCase()} businesses usually run ~${Math.round(d.benchmark_ratio * 100)}%, and mileage and home office show $0. I can't size what's missing from the return alone — connecting your bank is how we get the real number.`);
      } else if (s.strategy === "hire-your-kid") {
        parts.push(`**${n++} · Hire your kid(s) — ~${range(s.range)}/yr**\nWith ${s.detail.eligible_ages.length} of working age and a sole prop, paying them for real work shifts income from your bracket to their 0%. The wage has to be real and defensible — an expert sets it up right.`);
      } else if (s.strategy === "asset-depreciation") {
        parts.push(`**${n++} · Time your purchase — up to ${friendly(s.range[1])} first year**\nThat planned ${friendly(s.detail.deductible_amount)} purchase, placed in service by Dec 31, can be fully expensed this year (§179/bonus). Timing, not extra deduction — only if the business needs it.`);
      }
    });
    parts.push("I've put the plan on your tax hub for quick access. Where do you want to start?");
    return parts.join("\n\n");
  }

  function planChips() {
    const map = {
      "s-corp-election": ["Set up S-Corp", () => deepDive("s-corp-election")],
      "retirement-optimization": ["Evaluate retirement options", () => deepDive("retirement-optimization")],
      "quarterly-estimates": ["Schedule Q3 payment", () => deepDive("quarterly-estimates")],
      "deduction-optimization": ["Connect my bank", () => deepDive("deduction-optimization")],
      "hire-your-kid": ["Hire my kid(s)", () => deepDive("hire-your-kid")],
      "asset-depreciation": ["Time a purchase", () => deepDive("asset-depreciation")],
    };
    return SHOWN.map((s) => map[s.strategy]).filter(Boolean);
  }

  function revealPlan() {
    addAgent(planMessage(), 1400);
    setChips(planChips());
  }

  // ---------- deep dives ----------
  function backChips(excludeId) {
    return planChips().filter((c, i) => SHOWN[i] && SHOWN[i].strategy !== excludeId);
  }

  function remindLater(id) {
    const x = strat(id);
    const when = x && x.deadline ? "before " + mdy(x.deadline) : "before your next quarterly";
    addTurn({
      voice: `Done — I'll bring this back ${when}. It stays open on your plan.`,
      delay: 500,
      chips: backChips(id).concat([["View summary", showReceipt]]),
    });
  }
  function somethingDifferent(id) {
    addTurn({
      voice: "Sure — here's what else is on your plan.",
      delay: 400,
      chips: backChips(id).concat([["View summary", showReceipt]]),
    });
  }

  function deepDive(id) {
    openRail(); // hub plan rows land in the chat — make sure it's visible
    if (id === "s-corp-election") return diveSCorp();
    if (id === "retirement-optimization") return diveRetirement();
    if (id === "quarterly-estimates") return diveQuarterly();
    if (id === "deduction-optimization") return diveDeductions();
    if (id === "hire-your-kid") return diveHireKid();
    if (id === "asset-depreciation") return diveDepreciation();
  }

  function diveSCorp() {
    const s = strat("s-corp-election");
    const d = s.detail;
    addTurn({
      status: "Cut self-employment tax · from your plan",
      preVoice: "Here's the idea, in your numbers:",
      widget: W.compare({
        beforeLabel: "TODAY · SOLE PROP", before: exact(d.se_tax_today), beforeSub: "SE tax this year",
        afterLabel: "AS AN S-CORP", after: "~" + range(s.range), afterSub: "kept per year, net of costs",
        note: "Salary stays taxed · distributions don't · an expert sets the split",
        math: s.math,
      }),
      voice: `You'd split income into salary and distributions. Only the salary side pays the 15.3% tax. About ${exact(d.friction_cost)}/yr of payroll hassle is already netted out of that range.`,
      chips: [
        ["Book an expert", () => acceptSCorp()],
        ["What salary would I take?", askSalary],
        ["Remind me later", () => remindLater("s-corp-election")],
        ["Something different", () => somethingDifferent("s-corp-election")],
      ],
    });
  }

  function askSalary() {
    const s = strat("s-corp-election");
    addAgent(`That needs a reasonable-comp analysis. For your situation the typical band is **${exact(s.detail.salary_band[0])}–${exact(s.detail.salary_band[1])}**, but the exact number is an expert's to set — and to defend if the IRS asks. Want me to set up the appointment?`);
    setChips([
      ["Book an expert", () => acceptSCorp()],
      ["Leave it off my plan", () => skip("s-corp-election")],
    ]);
  }

  function acceptSCorp() {
    openExpertFlow({
      topic: "S-Corp election — reasonable comp analysis + 2027 paperwork",
      onBooked: (method) => {
        setStatus("s-corp-election", "accepted", `expert ${method} booked — reasonable comp + 2027 election`);
        addTurn({
          status: "Expert request sent · plan updated",
          voice: "Done — your S-Corp numbers went with the request. Nothing files without your sign-off.",
          delay: 500,
          chips: backChips("s-corp-election").concat([["View summary", showReceipt]]),
        });
      },
    });
  }

  function diveRetirement() {
    const s = strat("retirement-optimization");
    const top = s.detail.levels[s.detail.levels.length - 1];
    addTurn({
      status: "Save for retirement · from your plan",
      preVoice: "Here's what it looks like for you:",
      widget: W.compare({
        beforeLabel: "SAVED TODAY", before: "$0", beforeSub: "retirement contributions",
        afterLabel: `WITH ${friendly(top.contribution)} IN`, after: "−" + friendly(top.tax_deferred_this_year), afterSub: "off this year's tax",
        note: "Deferred, not erased — you pay it on withdrawal · plan must exist by Dec 31",
        math: s.math,
      }),
      voice: `A SEP could hold about ${friendly(s.detail.headroom.sep_max)} — a Solo 401(k) even more. That works out to ~${friendly(top.monthly_set_aside_rest_of_year)}/mo from here to December.`,
      chips: [
        ["Start guided setup", () => {
          setStatus("retirement-optimization", "accepted", "guided SEP/Solo 401(k) setup, plan by Dec 31");
          addAgent("Starting the guided setup — we'll pick SEP vs Solo 401(k) based on how much you want to shelter, then open the account with your custodian. I'll remind you well before Dec 31.");
          setChips(backChips("retirement-optimization").concat([["View summary", showReceipt]]));
        }],
        ["Remind me later", () => remindLater("retirement-optimization")],
        ["Something different", () => somethingDifferent("retirement-optimization")],
      ],
    });
  }

  function diveQuarterly() {
    const s = strat("quarterly-estimates");
    addTurn({
      status: "Stop the penalty · 100% sure, from your return",
      preVoice: "Here's the trade, in your numbers:",
      widget: W.compare({
        beforeLabel: "SKIP IT", before: exact(CUST.penalty) + "+", beforeSub: "penalty again next April",
        afterLabel: `PAY BY ${mdy(s.deadline).toUpperCase()}`, after: friendly(s.action_amount), afterSub: "penalty-proof, whatever income does",
        note: "Keyed to last year's tax · five minutes on IRS Direct Pay",
        math: s.math,
      }),
      voice: "Q1 and Q2 are paid on time. This is the sure thing — it locks in when you pay.",
      chips: [
        ["Pay & set a reminder", () => acceptQuarterly(s.action_amount, s.deadline)],
        ["My income changed", askIncome],
        ["Remind me later", () => remindLater("quarterly-estimates")],
        ["Something different", () => somethingDifferent("quarterly-estimates")],
      ],
    });
  }

  function acceptQuarterly(amount, deadline) {
    const remind = new Date(deadline + "T12:00:00");
    remind.setDate(remind.getDate() - 7);
    const rd = remind.toLocaleDateString("en-US", { month: "short", day: "numeric" });
    const p = plan.find((x) => x.id === "quarterly-estimates");
    p.action = amount;
    setStatus("quarterly-estimates", "accepted", `${exact(amount)} due ${mdy(deadline)} — reminder set for ${rd}`);
    addAgent(`Set. **${friendly(amount)} due ${mdy(deadline)}**, reminder on **${rd}**, paid via IRS Direct Pay. You're penalty-proof for the quarter.`);
    setChips(backChips("quarterly-estimates").concat([["View summary", showReceipt]]));
  }

  function askIncome() {
    addAgent("Roughly where is income heading this year? A ballpark is enough — I'll recompute your safe number from it.");
    setChips([
      ["~$110K", () => incomeWhatIf(110000)],
      ["~$150K", () => incomeWhatIf(150000)],
      ["About the same", () => addAgent(`Then ${friendly(strat("quarterly-estimates").action_amount)} stays your number — it's keyed to last year's tax, so it holds no matter what this year does.`) && setChips([["Pay & set a reminder", () => acceptQuarterly(strat("quarterly-estimates").action_amount, strat("quarterly-estimates").deadline)], ["Leave it off my plan", () => skip("quarterly-estimates")]])],
    ]);
  }

  function incomeWhatIf(income) {
    const snapped = Math.min(200000, Math.max(80000, Math.round(income / 5000) * 5000));
    const g = D.whatif_grid[snapped];
    if (!g) return fallback();
    learned.income_projection = snapped;
    const s = strat("quarterly-estimates");
    const lower = g.q3_target < s.action_amount;
    let msg = `At ~${friendly(snapped)} this year:\n\n• **Q3 safe number: ${friendly(g.q3_target)}** (was ${friendly(s.action_amount)})`;
    if (g.s_corp_range) msg += `\n• S-Corp range moves to **~${range(g.s_corp_range)}/yr**`;
    if (g.retirement_range) msg += `\n• Retirement deferral potential: up to **${friendly(g.retirement_range[1])}**`;
    msg += lower
      ? `\n\nThe lower number rides the 90%-of-this-year's-tax route and credits what you've already paid — the trade-off is a thinner margin if income recovers. Your call which number to pay.`
      : `\n\nYour safe-harbor number is keyed to last year's tax, so it doesn't go up — the extra would just be settled at filing.`;
    addAgent(msg);
    setChips([
      [`Pay ${friendly(g.q3_target)} & set a reminder`, () => acceptQuarterly(g.q3_target, g.q3_due || s.deadline)],
      [`Stick with ${friendly(s.action_amount)}`, () => acceptQuarterly(s.action_amount, s.deadline)],
      ["Leave it off my plan", () => skip("quarterly-estimates")],
    ]);
  }

  function diveDeductions() {
    const s = strat("deduction-optimization");
    const d = s.detail;
    const zeros = d.zero_claimed_lines.join(" and ");
    addTurn({
      status: "Find missed deductions · no number until you connect, by design",
      preVoice: "Here's the gap I can see from your return:",
      widget: W.compare({
        beforeLabel: "YOUR EXPENSES", before: Math.round(d.expense_ratio * 100) + "%", beforeSub: "of revenue",
        afterLabel: "TYPICAL", after: "~" + Math.round(d.benchmark_ratio * 100) + "%", afterSub: d.benchmark_label.toLowerCase(),
        note: `$0 claimed: ${zeros} · the return can't show what's missing`,
        math: s.math,
      }),
      voice: "I don't guess with your money. Connect your bank — free, via E3B Lite — and I'll track what's deductible all year.",
      chips: [
        ["Connect my bank", () => {
          setStatus("deduction-optimization", "accepted", "bank connected — year-round deduction tracking on");
          addAgent("Opening the connection now. From here I'll watch transactions and flag deductions as they happen — if something big turns up, I'll check in before your next quarterly instead of waiting.");
          setChips(backChips("deduction-optimization").concat([["View summary", showReceipt]]));
        }],
        ["Remind me later", () => remindLater("deduction-optimization")],
        ["Something different", () => somethingDifferent("deduction-optimization")],
      ],
    });
  }

  function diveHireKid() {
    const s = strat("hire-your-kid");
    const d = s.detail;
    addTurn({
      status: "Pay your kids · from your plan",
      preVoice: "Here's how it works for you:",
      widget: W.compare({
        beforeLabel: "PER KID, PER YEAR", before: exact(d.wage_guidance[0]) + "–" + exact(d.wage_guidance[1]), beforeSub: "real wages for real work",
        afterLabel: "SHIFTS TO THEIR 0%", after: "~" + range(s.range), afterSub: "off your tax, per year",
        note: `${d.eligible_ages.length} kid(s) in the 7–17 window · FICA-exempt on a sole prop`,
        math: s.math,
      }),
      voice: "The work has to be real and the wage defensible. Timesheets and a payroll record make it hold up — worth an expert to set up cleanly.",
      chips: [
        ["Book an expert", () => openExpertFlow({
          topic: "Hire my kids in the business — payroll + documentation setup",
          onBooked: (method) => {
            setStatus("hire-your-kid", "accepted", `expert ${method} booked — child payroll + documentation`);
            addTurn({
              status: "Expert request sent · plan updated",
              voice: "Done — the expert gets your numbers and sets the payroll up so the deduction holds.",
              delay: 500,
              chips: backChips("hire-your-kid").concat([["View summary", showReceipt]]),
            });
          },
        })],
        ["Remind me later", () => remindLater("hire-your-kid")],
        ["Something different", () => somethingDifferent("hire-your-kid")],
      ],
    });
  }

  function diveDepreciation() {
    const s = strat("asset-depreciation");
    const d = s.detail;
    addAgent(`Your planned **${friendly(d.deductible_amount)}** purchase, placed in service by **Dec 31**, can usually be written off in full this year via §179/bonus — about **${range(s.range)}** in first-year tax at your rate. One honest caveat: this is *timing*, not extra deduction — you're pulling the write-off forward, and it only makes sense if the business actually needs the equipment.`, undefined, mathHtml(s));
    setChips([
      ["Plan the purchase", () => {
        setStatus("asset-depreciation", "accepted", "capture the purchase in E3B once placed in service");
        addAgent("Set — I'll make sure it's captured once you buy, so the first-year write-off is claimed correctly before Dec 31.");
        setChips(backChips("asset-depreciation").concat([["View summary", showReceipt]]));
      }],
      ["Leave it off my plan", () => skip("asset-depreciation")],
    ]);
  }

  function skip(id) {
    setStatus(id, "skipped");
    addAgent("Easy — leaving it off your plan. It stays on your receipt as \"on the table\" if you change your mind.");
    if (!wrapped) setChips(backChips(id).concat([["View summary", showReceipt]]));
  }

  // ---------- free-text routing ----------
  function fallback() {
    addAgent("In this prototype I can go deep on the moves on your plan — the S-Corp election, retirement, your Q3 payment, and deductions — or run an income what-if (\"my income's heading to $140K\").");
    setChips(planChips());
  }

  function route(text) {
    const t = text.toLowerCase();
    const num = t.match(/\$?\s*(\d[\d,]*(?:\.\d+)?)\s*k?/);
    if (num && /(income|make|making|revenue|profit|heading|going)/.test(t)) {
      let v = parseFloat(num[1].replace(/,/g, ""));
      if (/k\b/.test(t) || v < 1000) v *= 1000;
      return incomeWhatIf(v);
    }
    if (/s[- ]?corp|salary|payroll|election/.test(t)) return diveSCorp();
    if (/retire|401|sep\b|ira\b|defer/.test(t)) return diveRetirement();
    if (/q3|quarter|estimat|safe|penalt|irs|pay/.test(t)) return diveQuarterly();
    if (/deduct|expense|write[- ]?off|bank|mileage|home office/.test(t)) return diveDeductions();
    if (/kid|child|son|daughter|family/.test(t)) {
      if (strat("hire-your-kid")) return diveHireKid();
      const k = D.hire_kid_per_kid;
      addAgent(`If your kids are 7–17 and do real work in the business — filing, social posts, admin — wages of ${exact(k.low_wage)}–${exact(k.high_wage)}/yr per kid shift income from your bracket to their 0%: roughly **${friendly(k.low)}–${friendly(k.high)} per kid, per year**. Two honest conditions: the work must be real and the wage defensible for their age — timesheets and a payroll record are what make it stick. Worth an expert to set up properly.`);
      return setChips(planChips());
    }
    if (/equip|vehicle|truck|laptop|computer|buy|purchase|deprecia|179/.test(t)) {
      if (strat("asset-depreciation")) return diveDepreciation();
      addAgent("A business purchase placed in service by **Dec 31** can usually be written off in full this year (§179/bonus) — but that's timing, not extra deduction, and it only makes sense if the business needs the thing. Give me the rough price and business-use share and I'll size the first-year saving.");
      return setChips(planChips());
    }
    if (/done|that's it|thanks|thank you|wrap/.test(t)) return showReceipt();
    return fallback();
  }

  const input = $("chat-text");
  const send = $("send-btn");
  input.addEventListener("input", () => send.classList.toggle("ready", input.value.trim().length > 0));
  function submit() {
    const v = input.value.trim();
    if (!v) return;
    input.value = "";
    send.classList.remove("ready");
    if (LIVE) { liveSubmit(v); return; }
    addUser(v);
    chipsEl.innerHTML = "";
    route(v);
  }
  send.addEventListener("click", submit);
  input.addEventListener("keydown", (e) => { if (e.key === "Enter") submit(); });

  // ---------- return picker (demo harness) ----------
  // Lists the sample Schedule C returns from AOS_RETURNS.manifest with a
  // readable summary; choosing one reloads the page as ?customer=<id> so both
  // scripted and live modes re-init cleanly on the selected return.
  const pickerBtn = () => $("picker-btn");
  const pickerPanel = () => $("picker-panel");

  function togglePicker(open) {
    const btn = pickerBtn(), panel = pickerPanel();
    if (!btn || !panel) return;
    const willOpen = (open === undefined) ? panel.hidden : open;
    panel.hidden = !willOpen;
    btn.setAttribute("aria-expanded", String(willOpen));
  }

  function selectReturn(id) {
    if (!id || id === CUST.id) { togglePicker(false); return; }
    const url = new URL(window.location.href);
    url.searchParams.set("customer", id);
    window.location.assign(url.toString());  // reload → boot re-inits on this return
  }

  function renderPicker() {
    if (!RET || !Array.isArray(RET.manifest)) return;  // no manifest (file:// w/o returns.gen.js)
    const btn = pickerBtn(), panel = pickerPanel(), label = $("picker-btn-label");
    if (!btn || !panel) return;
    const active = RET.manifest.find((m) => m.id === CUST.id);
    if (label && active) label.textContent = `${active.name} · ${compact(active.net_profit)} net`;

    panel.innerHTML = "";
    RET.manifest.forEach((m) => {
      const isActive = m.id === CUST.id;
      const fires = (m.fires || []).map((f) => `<span class="pk-tag">${SHORT[f.id] || f.id}</span>`).join("");
      const ctx = (m.needs_context || []).map((x) =>
        `<span class="pk-tag ctx" title="fires once the customer shares context">${SHORT[x] || x}</span>`).join("");
      const money = m.penalty > 0 ? `${exact(m.penalty)} penalty`
        : (m.balance_due > 0 ? `${exact(m.balance_due)} owed` : "on track");
      const row = document.createElement("button");
      row.className = "picker-row" + (isActive ? " active" : "");
      row.type = "button";
      row.setAttribute("role", "option");
      row.setAttribute("aria-selected", String(isActive));
      row.innerHTML =
        `<div class="pk-head"><span class="pk-name">${m.name}</span>` +
        `<span class="pk-meta">${m.filing_label} · ${m.state}</span></div>` +
        `<div class="pk-biz">${m.business}</div>` +
        `<div class="pk-nums">Schedule C · ${friendly(m.net_profit)} net · ${money}</div>` +
        `<div class="pk-fires">${fires}${ctx}</div>` +
        `<div class="pk-cta">${isActive ? "● Loaded" : "Load this return →"}</div>`;
      row.addEventListener("click", () => selectReturn(m.id));
      panel.appendChild(row);
    });
  }

  function wireIntroSwitch() {
    const right = document.querySelector(".ph-right");
    if (!right) return;
    const btn = document.createElement("button");
    btn.className = "btn-outline intro-switch";
    btn.type = "button";
    btn.title = "A/B: intro content framework (user-testing harness control)";
    btn.textContent = INTRO_VARIANT === "lean" ? "Intro: Lean" : "Intro: Full";
    btn.addEventListener("click", () => {
      const url = new URL(window.location.href);
      if (INTRO_VARIANT === "lean") url.searchParams.delete("intro");
      else url.searchParams.set("intro", "lean");
      window.location.assign(url.toString());
    });
    right.insertBefore(btn, right.querySelector(".return-picker"));
  }

  function wirePicker() {
    const btn = pickerBtn(), panel = pickerPanel();
    if (!btn || !panel) return;
    btn.addEventListener("click", (e) => { e.stopPropagation(); togglePicker(); });
    panel.addEventListener("click", (e) => e.stopPropagation());
    document.addEventListener("click", () => togglePicker(false));
    document.addEventListener("keydown", (e) => { if (e.key === "Escape") togglePicker(false); });
  }

  function wirePlanContinue() {
    const b = $("plan-continue");
    if (!b) return;
    b.addEventListener("click", () => {
      openRail();
      const box = $("chat-text"); if (box) box.focus({ preventScroll: true });
    });
  }

  function wireHeadlineMath() {
    // Wired once (renderHub re-runs on every status change and only fills content).
    const how = $("proj-how"), panel = $("proj-math");
    if (how && panel) how.addEventListener("click", () => { panel.hidden = !panel.hidden; });
  }

  // ---------- expert-match overlay (DIWM TY25 Expert Match flow) ----------
  // Any "connect with an expert" door opens this side-panel overlay:
  // Connect → topic → channel (callback/chat/appointment) → confirmation.
  // Booking IS the customer confirmation (guardrail: confirmation before
  // commitment) — the plan status updates only in onBooked.
  let EO = null;
  let eoState = {};
  function eoEl() {
    if (EO) return EO;
    EO = document.createElement("div");
    EO.className = "expert-overlay";
    document.querySelector(".chat-rail").appendChild(EO);
    return EO;
  }
  function openExpertFlow(opts) {
    eoState = { topic: opts.topic, onBooked: opts.onBooked, step: 1 };
    eoRender();
    requestAnimationFrame(() => eoEl().classList.add("open"));
  }
  function closeExpertFlow() { if (EO) EO.classList.remove("open"); }
  function eoTop(withBack) {
    return `<div class="eo-top">${withBack ? '<button class="eo-back" data-eo="back">‹ Back</button>' : '<span class="eo-title-sm">Help</span>'}` +
      `<button class="icon-btn" data-eo="close" aria-label="Close"><svg viewBox="0 0 20 20" width="19" height="19"><path d="M5 5l10 10M15 5L5 15" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg></button></div>`;
  }
  function eoRender() {
    const el = eoEl();
    if (eoState.step === 1) {
      el.innerHTML = eoTop(false) + `<div class="eo-body">` +
        `<div class="eo-h1">Connect with an expert</div>` +
        `<div class="eo-card"><span class="eo-pill-note">🕐 Available in 5 mins</span>` +
        `<div class="eo-avatars"><span class="eo-avatar" style="background:#7a5195">MC</span><span class="eo-avatar" style="background:#ef5675">RB</span><span class="eo-avatar" style="background:#ffa600">JW</span></div>` +
        `<div class="eo-name">Experts online now</div><button class="eo-cta" data-eo="next">Start a call or chat</button></div>` +
        `<div class="eo-card"><span class="eo-avatar" style="background:#374c80">SL</span>` +
        `<div class="eo-name">Match with a tax expert</div><div class="eo-sub">We'll match you with an expert that's right for you and your taxes</div>` +
        `<button class="eo-cta" data-eo="next">Find my expert</button></div>` +
        `<button class="eo-link" type="button">Contact history</button></div>`;
    } else if (eoState.step === 2) {
      el.innerHTML = eoTop(true) + `<div class="eo-body">` +
        `<div class="eo-icon-circle">💬</div>` +
        `<div class="eo-h2" style="text-align:center">What can we help you with?</div>` +
        `<textarea class="eo-textarea" id="eo-topic">${esc(eoState.topic)}</textarea>` +
        `<span class="eo-chars">144 characters</span>` +
        `<label class="eo-check"><input type="checkbox"> Ayuda en Español</label>` +
        `<button class="eo-cta" style="max-width:none" data-eo="next">Continue</button></div>`;
    } else if (eoState.step === 3) {
      el.innerHTML = eoTop(true) + `<div class="eo-body">` +
        `<div class="eo-said">You said<br><b>${esc(eoState.topic)}</b> ✏️</div>` +
        `<div class="eo-h2">How would you like to connect with us?</div>` +
        `<div class="eo-opt"><div class="eo-opt-head">📞 Callback <span class="eo-badge">RECOMMENDED</span></div><div class="eo-sub">You're next in line.</div>` +
        `<button class="eo-cta" data-eo="book" data-method="callback">Have us call you</button><span class="eo-wait">🕐 Wait time 5 min</span></div>` +
        `<div class="eo-opt"><div class="eo-opt-head">💬 Chat</div><div class="eo-sub">Start a conversation.</div>` +
        `<button class="eo-cta" data-eo="book" data-method="chat">Chat with us</button><span class="eo-wait">We'll chat with you in about 13 hr 30 min</span></div>` +
        `<div class="eo-opt"><div class="eo-opt-head">📅 Appointment</div><div class="eo-sub">Pick a time that's best for you.</div>` +
        `<button class="eo-cta" data-eo="book" data-method="appointment">Schedule appointment</button></div></div>`;
    } else {
      const m = { callback: "We'll call you in about 5 minutes.", chat: "We'll start the chat — about 13 hr 30 min.", appointment: "You'll pick the time — invite is on its way." }[eoState.method];
      el.innerHTML = eoTop(false) + `<div class="eo-body"><div class="eo-done"><div class="eo-icon-circle">✅</div>` +
        `<div class="eo-h2">You're set</div><div class="eo-sub">${esc(m)}<br>Your plan numbers go with the request — nothing to re-explain.</div>` +
        `<button class="eo-cta" data-eo="finish">Back to your plan</button></div></div>`;
    }
    el.querySelectorAll("[data-eo]").forEach((b) => b.addEventListener("click", () => {
      const a = b.dataset.eo;
      if (a === "close") closeExpertFlow();
      else if (a === "back") { eoState.step--; eoRender(); }
      else if (a === "next") { const t = el.querySelector("#eo-topic"); if (t) eoState.topic = t.value; eoState.step++; eoRender(); }
      else if (a === "book") { eoState.method = b.dataset.method; eoState.step = 4; eoRender(); }
      else if (a === "finish") { closeExpertFlow(); if (eoState.onBooked) eoState.onBooked(eoState.method); }
    }));
  }

  // ---------- boot ----------
  // Seed the hub from the active return's AOS_DATA immediately (no flash of
  // empty state), wire the picker, then decide scripted-demo vs. live-backend
  // once we know whether ui/server.py is reachable.
  const heroShown = renderHero();
  renderHub();          // populate the (hidden) plan container so the reveal is instant
  renderPicker();
  wirePicker();
  wireIntroSwitch();
  wireHeadlineMath();
  wirePlanContinue();
  wireHero();
  wireRail();
  const sr0 = summaryRow(); if (sr0) sr0.hidden = true;  // no "View summary" until a plan exists
  (async function boot() {
    // Detect mode for the pill. When the hero is shown, DON'T start the
    // conversation or reveal the plan yet — the customer begins from the hero's
    // "Secure all savings" CTA (beginOnboarding). Only if there's no hero to
    // click (e.g. a return with no benchmark) do we fall back to auto-start —
    // and since the conversation starts itself, open the rail so it's visible.
    LIVE = await checkLiveMode();
    setModePill(LIVE);
    if (!heroShown) { openRail(); introStarted = true; if (LIVE) startLiveSession(); else start(); }
  })();
})();
