// GENERATED by ui/build_returns.py — do not edit. Every $ traces to calculators/.
window.AOS_RETURNS = {
  "active_default": "marcus",
  "as_of": "2026-09-04",
  "manifest": [
    {
      "id": "marcus",
      "name": "Marcus Webb",
      "business": "Independent operations consultant (single-member LLC)",
      "state": "CO",
      "filing_label": "Single",
      "entity": "Schedule C (sole prop)",
      "net_profit": 135000,
      "gross_receipts": 148500,
      "balance_due": 4200,
      "penalty": 340,
      "fires": [
        {
          "id": "s-corp-election",
          "range": [
            4100,
            7200
          ]
        },
        {
          "id": "retirement-optimization",
          "range": [
            2200,
            5500
          ]
        },
        {
          "id": "quarterly-estimates",
          "range": [
            340,
            850
          ]
        },
        {
          "id": "deduction-optimization",
          "range": null
        }
      ],
      "needs_context": [
        "hire-your-kid"
      ]
    },
    {
      "id": "priya",
      "name": "Priya Nair",
      "business": "Independent IT / software consultant",
      "state": "NY",
      "filing_label": "HoH",
      "entity": "Schedule C (sole prop)",
      "net_profit": 185000,
      "gross_receipts": 201000,
      "balance_due": 9250,
      "penalty": 1100,
      "fires": [
        {
          "id": "s-corp-election",
          "range": [
            6200,
            10500
          ]
        },
        {
          "id": "retirement-optimization",
          "range": [
            2400,
            8300
          ]
        },
        {
          "id": "hire-your-kid",
          "range": [
            4600,
            9200
          ]
        },
        {
          "id": "quarterly-estimates",
          "range": [
            1100,
            2750
          ]
        }
      ],
      "needs_context": []
    },
    {
      "id": "theo",
      "name": "Theo Alvarez",
      "business": "Freelance photographer & videographer",
      "state": "CO",
      "filing_label": "Single",
      "entity": "Schedule C (sole prop)",
      "net_profit": 78000,
      "gross_receipts": 84500,
      "balance_due": 3670,
      "penalty": 280,
      "fires": [
        {
          "id": "retirement-optimization",
          "range": [
            1200,
            1700
          ]
        },
        {
          "id": "quarterly-estimates",
          "range": [
            280,
            700
          ]
        },
        {
          "id": "deduction-optimization",
          "range": null
        }
      ],
      "needs_context": [
        "hire-your-kid"
      ]
    },
    {
      "id": "gabriela",
      "name": "Gabriela Santos",
      "business": "Handmade jewelry & goods (online shop)",
      "state": "FL",
      "filing_label": "MFJ",
      "entity": "Schedule C (sole prop)",
      "net_profit": 120000,
      "gross_receipts": 131000,
      "balance_due": -50,
      "penalty": 0,
      "fires": [
        {
          "id": "hire-your-kid",
          "range": [
            4400,
            8600
          ]
        },
        {
          "id": "s-corp-election",
          "range": [
            3500,
            6300
          ]
        },
        {
          "id": "retirement-optimization",
          "range": [
            2200,
            4900
          ]
        },
        {
          "id": "deduction-optimization",
          "range": null
        }
      ],
      "needs_context": []
    }
  ],
  "data": {
    "marcus": {
      "as_of": "2026-09-04",
      "customer": {
        "id": "marcus",
        "name": "Marcus Webb",
        "first_name": "Marcus",
        "filing_status": "single",
        "state": "CO",
        "business": "Independent operations consultant (single-member LLC)",
        "net_profit": 135000,
        "gross_receipts": 148500,
        "total_tax": 32400,
        "balance_due": 4200,
        "penalty": 340,
        "filed_date": "2026-04-10",
        "product": "TurboTax Self-Employed",
        "hook": {
          "channel": "email",
          "copy": "You owed $4,200 in April plus a $340 penalty on $135K of consulting profit. That balance-due surprise is fixable \u2014 and it's not the biggest lever here. See your plan \u2192"
        }
      },
      "analysis": {
        "customer": "marcus",
        "name": "Marcus Webb",
        "as_of": "2026-09-04",
        "tax_year_planning": 2026,
        "shown": [
          {
            "strategy": "s-corp-election",
            "label": "Elect S-Corp (reasonable comp split)",
            "fires": true,
            "needs_context": false,
            "reason": "Net profit $135,000 \u2014 all of it paid 15.3% SE tax as a sole prop",
            "range": [
              4100,
              7200
            ],
            "range_kind": "recurring_annual",
            "deadline": "2027-03-15",
            "deadline_note": "2026 window passed (Mar 16) \u2014 election would be set up for tax year 2027",
            "door": "expert (reasonable-comp analysis + election filing)",
            "expert_gated": true,
            "detail": {
              "se_tax_today": 19075,
              "salary_band": [
                67500,
                87750
              ],
              "friction_cost": 1500,
              "savings_range": [
                4100,
                7200
              ]
            },
            "math": {
              "route": "SE tax you pay today, minus payroll tax on a reasonable salary, minus payroll/filing friction \u2014 computed at both ends of the salary band. Higher salary \u2192 smaller saving.",
              "rows": [
                {
                  "label": "Net profit (Schedule C, 2025)",
                  "value": 135000,
                  "fmt": "money"
                },
                {
                  "label": "SE tax today (15.3% on 92.35% of profit)",
                  "value": 19075,
                  "fmt": "money"
                },
                {
                  "label": "Reasonable-salary band (50\u201365% of profit)",
                  "value": [
                    67500,
                    87750
                  ],
                  "fmt": "money_range"
                },
                {
                  "label": "Payroll tax across that band",
                  "value": [
                    10328,
                    13426
                  ],
                  "fmt": "money_range"
                },
                {
                  "label": "Annual payroll + filing friction (netted out)",
                  "value": 1500,
                  "fmt": "money"
                },
                {
                  "label": "Savings range (recurring, annual)",
                  "value": [
                    4100,
                    7200
                  ],
                  "fmt": "money_range"
                }
              ]
            },
            "costs_unprompted": [
              "monthly payroll to run",
              "a separate business return (1120-S)",
              "IRS watches for a defensible 'reasonable salary'",
              "~$1,500/yr payroll + filing friction (already netted out of the range)"
            ]
          },
          {
            "strategy": "retirement-optimization",
            "label": "Retirement contribution (SEP / Solo 401(k))",
            "fires": true,
            "needs_context": false,
            "reason": "$0 contributed against ~$25,093 of SEP headroom",
            "range": [
              2200,
              5500
            ],
            "range_kind": "deferral_not_permanent",
            "deadline": "2026-12-31",
            "deadline_note": "The plan must exist by Dec 31 \u2014 months before filing would ever show you this. (SEP contributions can land by the filing deadline.)",
            "door": "guided setup; expert optional for plan choice",
            "detail": {
              "marginal_rate": 0.22,
              "headroom": {
                "sep_max": 25093,
                "solo401k_max": 49593
              },
              "levels": [
                {
                  "contribution": 10000,
                  "tax_deferred_this_year": 2200,
                  "monthly_set_aside_rest_of_year": 1667
                },
                {
                  "contribution": 20000,
                  "tax_deferred_this_year": 4400,
                  "monthly_set_aside_rest_of_year": 3333
                },
                {
                  "contribution": 25093,
                  "tax_deferred_this_year": 5500,
                  "monthly_set_aside_rest_of_year": 4182
                }
              ]
            },
            "math": {
              "route": "Contribution \u00d7 your marginal tax rate = tax deferred this year. Deferral, not free money \u2014 tax is paid later on withdrawal.",
              "rows": [
                {
                  "label": "Net profit (Schedule C, 2025)",
                  "value": 135000,
                  "fmt": "money"
                },
                {
                  "label": "SEP headroom (~20% of profit less \u00bd SE tax)",
                  "value": 25093,
                  "fmt": "money"
                },
                {
                  "label": "Solo 401(k) headroom (adds employee deferral)",
                  "value": 49593,
                  "fmt": "money"
                },
                {
                  "label": "Contributed so far",
                  "value": 0,
                  "fmt": "money"
                },
                {
                  "label": "Your marginal rate",
                  "value": 0.22,
                  "fmt": "pct"
                },
                {
                  "label": "Smallest level: $10,000 \u00d7 rate",
                  "value": 2200,
                  "fmt": "money"
                },
                {
                  "label": "Max SEP level: $25,093 \u00d7 rate",
                  "value": 5500,
                  "fmt": "money"
                },
                {
                  "label": "Deferred this year (range)",
                  "value": [
                    2200,
                    5500
                  ],
                  "fmt": "money_range"
                }
              ]
            },
            "framing_required": "Deferral, not free money \u2014 tax is paid later on withdrawal, not erased."
          },
          {
            "strategy": "quarterly-estimates",
            "label": "Quarterly safe-harbor payments",
            "fires": true,
            "needs_context": false,
            "reason": "$340 underpayment penalty and $4,200 balance due on the TY25 return",
            "range": [
              340,
              850
            ],
            "range_kind": "penalty_avoided",
            "action_amount": 8000,
            "deadline": "2026-09-15",
            "door": "self-serve (IRS Direct Pay) + reminder",
            "detail": {
              "safe_harbor_total": 32400,
              "assumed_withholding": 0,
              "needed_via_estimates": 32400,
              "route": "100% of last year's tax",
              "per_quarter": 8100,
              "quarters": [
                {
                  "q": 1,
                  "due": "2026-04-15",
                  "target": 8100,
                  "paid": 8200,
                  "status": "paid"
                },
                {
                  "q": 2,
                  "due": "2026-06-15",
                  "target": 8100,
                  "paid": 8200,
                  "status": "paid"
                },
                {
                  "q": 3,
                  "due": "2026-09-15",
                  "target": 8000,
                  "paid": 0,
                  "status": "due"
                },
                {
                  "q": 4,
                  "due": "2027-01-15",
                  "target": 8000,
                  "paid": 0,
                  "status": "due"
                }
              ],
              "next": {
                "q": 3,
                "due": "2026-09-15",
                "target": 8000,
                "paid": 0,
                "status": "due"
              },
              "missed": [],
              "withholding_note": "No W-2 withholding on the return \u2014 estimates carry the whole safe harbor."
            },
            "math": {
              "route": "Cheapest penalty-proof total = the safe-harbor % of last year's tax. Withholding and payments already made count; remaining quarters split what's left.",
              "rows": [
                {
                  "label": "Last year's total tax (2025 return)",
                  "value": 32400,
                  "fmt": "money"
                },
                {
                  "label": "Safe-harbor route",
                  "value": "100% of last year's tax",
                  "fmt": "text"
                },
                {
                  "label": "Penalty-proof total for the year",
                  "value": 32400,
                  "fmt": "money"
                },
                {
                  "label": "W-2 withholding assumed (counts toward it)",
                  "value": 0,
                  "fmt": "money"
                },
                {
                  "label": "Needed via estimated payments",
                  "value": 32400,
                  "fmt": "money"
                },
                {
                  "label": "Paid so far this year",
                  "value": 16400,
                  "fmt": "money"
                },
                {
                  "label": "Next payment (Q3, remaining quarters split the gap)",
                  "value": 8000,
                  "fmt": "money"
                },
                {
                  "label": "Penalty avoided (last year's, to ~2.5\u00d7 if income grows)",
                  "value": [
                    340,
                    850
                  ],
                  "fmt": "money_range"
                }
              ]
            }
          },
          {
            "strategy": "deduction-optimization",
            "label": "Deduction tracking (bank connect)",
            "fires": true,
            "needs_context": false,
            "reason": "Expenses run 9% of revenue; management consulting businesses typically run ~14%",
            "range": null,
            "range_kind": "gated_no_presize",
            "gated": true,
            "gate_rule": "Never show a $ range from the return alone. The pitch is the gap + the connect.",
            "deadline": null,
            "door": "bank connect via E3B Lite (free)",
            "math": {
              "route": "No dollar range by design \u2014 the return only shows what made it in, so what's missing can't be sized from it. The gap vs. benchmark is the signal; connecting the bank gets the real number.",
              "rows": [
                {
                  "label": "Business expenses claimed (Schedule C)",
                  "value": 13500,
                  "fmt": "money"
                },
                {
                  "label": "Gross receipts",
                  "value": 148500,
                  "fmt": "money"
                },
                {
                  "label": "Your expense ratio",
                  "value": 0.091,
                  "fmt": "pct"
                },
                {
                  "label": "Typical for management consulting",
                  "value": 0.14,
                  "fmt": "pct"
                },
                {
                  "label": "Lines claimed at $0",
                  "value": "vehicle mileage, home office",
                  "fmt": "text"
                }
              ]
            },
            "detail": {
              "expense_ratio": 0.091,
              "benchmark_ratio": 0.14,
              "benchmark_label": "Management consulting",
              "zero_claimed_lines": [
                "vehicle mileage",
                "home office"
              ],
              "commonly_missed": [
                "home office",
                "business mileage",
                "software and subscriptions",
                "phone and internet",
                "self-employed health insurance premiums"
              ],
              "se_health_note": null
            }
          }
        ],
        "suppressed_below_materiality": [],
        "needs_context": [
          {
            "strategy": "hire-your-kid",
            "context_needed": "household \u2014 kids and ages (onboarding question)"
          }
        ],
        "not_fired": [],
        "onboarding_gaps": [
          "income_trajectory",
          "health_coverage",
          "household_kids_ages",
          "planned_purchases",
          "optimize_for",
          "big_changes"
        ]
      },
      "benchmark": {
        "estimate": 6000,
        "range": [
          4000,
          8100
        ],
        "left_on_table_last_year": 340,
        "segment_label": "full-time solopreneurs, $50K\u2013$200K net",
        "note": "Segment-average first-year tax savings from a proactive plan \u2014 a rough estimate, not a personalized figure. Your real number comes from your plan after onboarding.",
        "math": {
          "route": "Segment average only: a proactive tax plan saves full-time solos roughly 3\u20136% of net profit in year one ($4,000\u2013$8,100 here). This is a benchmark, not your personalized number \u2014 that comes from your plan after a couple of questions.",
          "rows": [
            {
              "label": "Your 2025 net profit (Schedule C)",
              "value": 135000,
              "fmt": "money"
            },
            {
              "label": "Estimated first-year savings (midpoint of range)",
              "value": 6000,
              "fmt": "money"
            },
            {
              "label": "Underpayment penalty you paid last year",
              "value": 340,
              "fmt": "money"
            }
          ]
        }
      },
      "whatif_grid": {
        "80000": {
          "q3_target": 0,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            1800,
            3700
          ],
          "retirement_range": [
            1200,
            1800
          ]
        },
        "85000": {
          "q3_target": 0,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            2100,
            4000
          ],
          "retirement_range": [
            1200,
            1900
          ]
        },
        "90000": {
          "q3_target": 86,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            2300,
            4300
          ],
          "retirement_range": [
            1200,
            2000
          ]
        },
        "95000": {
          "q3_target": 726,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            2500,
            4700
          ],
          "retirement_range": [
            2200,
            3900
          ]
        },
        "100000": {
          "q3_target": 1405,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            2700,
            5000
          ],
          "retirement_range": [
            2200,
            4100
          ]
        },
        "105000": {
          "q3_target": 2084,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            2900,
            5300
          ],
          "retirement_range": [
            2200,
            4300
          ]
        },
        "110000": {
          "q3_target": 2763,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            3100,
            5600
          ],
          "retirement_range": [
            2200,
            4500
          ]
        },
        "115000": {
          "q3_target": 3442,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            3300,
            6000
          ],
          "retirement_range": [
            2200,
            4700
          ]
        },
        "120000": {
          "q3_target": 4121,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            3500,
            6300
          ],
          "retirement_range": [
            2200,
            4900
          ]
        },
        "125000": {
          "q3_target": 4800,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            3700,
            6600
          ],
          "retirement_range": [
            2200,
            5100
          ]
        },
        "130000": {
          "q3_target": 5479,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            3900,
            6900
          ],
          "retirement_range": [
            2200,
            5300
          ]
        },
        "135000": {
          "q3_target": 6158,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            4100,
            7200
          ],
          "retirement_range": [
            2200,
            5500
          ]
        },
        "140000": {
          "q3_target": 6837,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            4400,
            7600
          ],
          "retirement_range": [
            2200,
            5700
          ]
        },
        "145000": {
          "q3_target": 7516,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            4600,
            7900
          ],
          "retirement_range": [
            2200,
            5900
          ]
        },
        "150000": {
          "q3_target": 8000,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            4800,
            8200
          ],
          "retirement_range": [
            2200,
            6100
          ]
        },
        "155000": {
          "q3_target": 8000,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            5000,
            8500
          ],
          "retirement_range": [
            2200,
            6300
          ]
        },
        "160000": {
          "q3_target": 8000,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            5200,
            8900
          ],
          "retirement_range": [
            2200,
            6500
          ]
        },
        "165000": {
          "q3_target": 8000,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            5400,
            9200
          ],
          "retirement_range": [
            2200,
            6700
          ]
        },
        "170000": {
          "q3_target": 8000,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            5600,
            9500
          ],
          "retirement_range": [
            2400,
            7600
          ]
        },
        "175000": {
          "q3_target": 8000,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            5800,
            9800
          ],
          "retirement_range": [
            2400,
            7800
          ]
        },
        "180000": {
          "q3_target": 8000,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            6000,
            10200
          ],
          "retirement_range": [
            2400,
            8000
          ]
        },
        "185000": {
          "q3_target": 8000,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            6200,
            10500
          ],
          "retirement_range": [
            2400,
            8300
          ]
        },
        "190000": {
          "q3_target": 8000,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            6500,
            10800
          ],
          "retirement_range": [
            2400,
            8500
          ]
        },
        "195000": {
          "q3_target": 8000,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            6700,
            11100
          ],
          "retirement_range": [
            2400,
            8700
          ]
        },
        "200000": {
          "q3_target": 8000,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            6800,
            11400
          ],
          "retirement_range": [
            2400,
            8900
          ]
        }
      },
      "hire_kid_per_kid": {
        "low_wage": 6000,
        "high_wage": 12000,
        "low": 2200,
        "high": 4300
      }
    },
    "priya": {
      "as_of": "2026-09-04",
      "customer": {
        "id": "priya",
        "name": "Priya Nair",
        "first_name": "Priya",
        "filing_status": "head_of_household",
        "state": "NY",
        "business": "Independent IT / software consultant",
        "net_profit": 185000,
        "gross_receipts": 201000,
        "total_tax": 47250,
        "balance_due": 9250,
        "penalty": 1100,
        "filed_date": "2026-04-14",
        "product": "TurboTax Self-Employed",
        "hook": {
          "channel": "email",
          "copy": "You owed $9,250 in April plus an $1,100 penalty on $185K of consulting profit. There are bigger levers here than the quarterly fix \u2014 see your plan \u2192"
        }
      },
      "analysis": {
        "customer": "priya",
        "name": "Priya Nair",
        "as_of": "2026-09-04",
        "tax_year_planning": 2026,
        "shown": [
          {
            "strategy": "s-corp-election",
            "label": "Elect S-Corp (reasonable comp split)",
            "fires": true,
            "needs_context": false,
            "reason": "Net profit $185,000 \u2014 all of it paid 15.3% SE tax as a sole prop",
            "range": [
              6200,
              10500
            ],
            "range_kind": "recurring_annual",
            "deadline": "2027-03-15",
            "deadline_note": "2026 window passed (Mar 16) \u2014 election would be set up for tax year 2027",
            "door": "expert (reasonable-comp analysis + election filing)",
            "expert_gated": true,
            "detail": {
              "se_tax_today": 26140,
              "salary_band": [
                92500,
                120250
              ],
              "friction_cost": 1500,
              "savings_range": [
                6200,
                10500
              ]
            },
            "math": {
              "route": "SE tax you pay today, minus payroll tax on a reasonable salary, minus payroll/filing friction \u2014 computed at both ends of the salary band. Higher salary \u2192 smaller saving.",
              "rows": [
                {
                  "label": "Net profit (Schedule C, 2025)",
                  "value": 185000,
                  "fmt": "money"
                },
                {
                  "label": "SE tax today (15.3% on 92.35% of profit)",
                  "value": 26140,
                  "fmt": "money"
                },
                {
                  "label": "Reasonable-salary band (50\u201365% of profit)",
                  "value": [
                    92500,
                    120250
                  ],
                  "fmt": "money_range"
                },
                {
                  "label": "Payroll tax across that band",
                  "value": [
                    14152,
                    18398
                  ],
                  "fmt": "money_range"
                },
                {
                  "label": "Annual payroll + filing friction (netted out)",
                  "value": 1500,
                  "fmt": "money"
                },
                {
                  "label": "Savings range (recurring, annual)",
                  "value": [
                    6200,
                    10500
                  ],
                  "fmt": "money_range"
                }
              ]
            },
            "costs_unprompted": [
              "monthly payroll to run",
              "a separate business return (1120-S)",
              "IRS watches for a defensible 'reasonable salary'",
              "~$1,500/yr payroll + filing friction (already netted out of the range)"
            ]
          },
          {
            "strategy": "retirement-optimization",
            "label": "Retirement contribution (SEP / Solo 401(k))",
            "fires": true,
            "needs_context": false,
            "reason": "$0 contributed against ~$34,386 of SEP headroom",
            "range": [
              2400,
              8300
            ],
            "range_kind": "deferral_not_permanent",
            "deadline": "2026-12-31",
            "deadline_note": "The plan must exist by Dec 31 \u2014 months before filing would ever show you this. (SEP contributions can land by the filing deadline.)",
            "door": "guided setup; expert optional for plan choice",
            "detail": {
              "marginal_rate": 0.24,
              "headroom": {
                "sep_max": 34386,
                "solo401k_max": 58886
              },
              "levels": [
                {
                  "contribution": 10000,
                  "tax_deferred_this_year": 2400,
                  "monthly_set_aside_rest_of_year": 1667
                },
                {
                  "contribution": 20000,
                  "tax_deferred_this_year": 4800,
                  "monthly_set_aside_rest_of_year": 3333
                },
                {
                  "contribution": 34386,
                  "tax_deferred_this_year": 8300,
                  "monthly_set_aside_rest_of_year": 5731
                }
              ]
            },
            "math": {
              "route": "Contribution \u00d7 your marginal tax rate = tax deferred this year. Deferral, not free money \u2014 tax is paid later on withdrawal.",
              "rows": [
                {
                  "label": "Net profit (Schedule C, 2025)",
                  "value": 185000,
                  "fmt": "money"
                },
                {
                  "label": "SEP headroom (~20% of profit less \u00bd SE tax)",
                  "value": 34386,
                  "fmt": "money"
                },
                {
                  "label": "Solo 401(k) headroom (adds employee deferral)",
                  "value": 58886,
                  "fmt": "money"
                },
                {
                  "label": "Contributed so far",
                  "value": 0,
                  "fmt": "money"
                },
                {
                  "label": "Your marginal rate",
                  "value": 0.24,
                  "fmt": "pct"
                },
                {
                  "label": "Smallest level: $10,000 \u00d7 rate",
                  "value": 2400,
                  "fmt": "money"
                },
                {
                  "label": "Max SEP level: $34,386 \u00d7 rate",
                  "value": 8300,
                  "fmt": "money"
                },
                {
                  "label": "Deferred this year (range)",
                  "value": [
                    2400,
                    8300
                  ],
                  "fmt": "money_range"
                }
              ]
            },
            "framing_required": "Deferral, not free money \u2014 tax is paid later on withdrawal, not erased."
          },
          {
            "strategy": "hire-your-kid",
            "label": "Hire your child",
            "fires": true,
            "needs_context": false,
            "reason": "2 kid(s) in the FICA-exempt window (7\u201317) on a sole prop",
            "range": [
              4600,
              9200
            ],
            "range_kind": "recurring_annual",
            "deadline": null,
            "deadline_note": "Wages must be paid in-year for in-year deduction",
            "door": "expert (payroll setup + documentation)",
            "detail": {
              "eligible_ages": [
                12,
                15
              ],
              "wage_guidance": [
                6000,
                12000
              ],
              "max_wage_no_income_tax": 16100
            },
            "math": {
              "route": "Wages for real work are a business deduction: you save your marginal rate + SE tax on the shifted profit; the child owes ~$0 under the standard deduction, and no FICA under 18 on a parent's sole prop.",
              "rows": [
                {
                  "label": "Kids in the 7\u201317 window",
                  "value": "2 (ages 12, 15)",
                  "fmt": "text"
                },
                {
                  "label": "Typical defensible wage per kid",
                  "value": [
                    6000,
                    12000
                  ],
                  "fmt": "money_range"
                },
                {
                  "label": "Your marginal rate",
                  "value": 0.24,
                  "fmt": "pct"
                },
                {
                  "label": "Effective SE rate avoided",
                  "value": 0.1412955,
                  "fmt": "pct"
                },
                {
                  "label": "Savings per kid (wage \u00d7 combined rate)",
                  "value": [
                    2300,
                    4600
                  ],
                  "fmt": "money_range"
                },
                {
                  "label": "Across 2 kid(s), per year",
                  "value": [
                    4600,
                    9200
                  ],
                  "fmt": "money_range"
                }
              ]
            },
            "costs_unprompted": [
              "the work must be real and the wage defensible for the child's age",
              "timesheets and a payroll record are what make it stick in an audit"
            ]
          },
          {
            "strategy": "quarterly-estimates",
            "label": "Quarterly safe-harbor payments",
            "fires": true,
            "needs_context": false,
            "reason": "$1100 underpayment penalty and $9,250 balance due on the TY25 return",
            "range": [
              1100,
              2750
            ],
            "range_kind": "penalty_avoided",
            "action_amount": 16488,
            "deadline": "2026-09-15",
            "door": "self-serve (IRS Direct Pay) + reminder",
            "detail": {
              "safe_harbor_total": 51975,
              "assumed_withholding": 0,
              "needed_via_estimates": 51975,
              "route": "110% of last year's tax",
              "per_quarter": 12994,
              "quarters": [
                {
                  "q": 1,
                  "due": "2026-04-15",
                  "target": 12994,
                  "paid": 9500,
                  "status": "missed"
                },
                {
                  "q": 2,
                  "due": "2026-06-15",
                  "target": 12994,
                  "paid": 9500,
                  "status": "missed"
                },
                {
                  "q": 3,
                  "due": "2026-09-15",
                  "target": 16488,
                  "paid": 0,
                  "status": "due"
                },
                {
                  "q": 4,
                  "due": "2027-01-15",
                  "target": 16488,
                  "paid": 0,
                  "status": "due"
                }
              ],
              "next": {
                "q": 3,
                "due": "2026-09-15",
                "target": 16488,
                "paid": 0,
                "status": "due"
              },
              "missed": [
                {
                  "q": 1,
                  "due": "2026-04-15",
                  "target": 12994,
                  "paid": 9500,
                  "status": "missed"
                },
                {
                  "q": 2,
                  "due": "2026-06-15",
                  "target": 12994,
                  "paid": 9500,
                  "status": "missed"
                }
              ],
              "withholding_note": "No W-2 withholding on the return \u2014 estimates carry the whole safe harbor."
            },
            "math": {
              "route": "Cheapest penalty-proof total = the safe-harbor % of last year's tax. Withholding and payments already made count; remaining quarters split what's left.",
              "rows": [
                {
                  "label": "Last year's total tax (2025 return)",
                  "value": 47250,
                  "fmt": "money"
                },
                {
                  "label": "Safe-harbor route",
                  "value": "110% of last year's tax",
                  "fmt": "text"
                },
                {
                  "label": "Penalty-proof total for the year",
                  "value": 51975,
                  "fmt": "money"
                },
                {
                  "label": "W-2 withholding assumed (counts toward it)",
                  "value": 0,
                  "fmt": "money"
                },
                {
                  "label": "Needed via estimated payments",
                  "value": 51975,
                  "fmt": "money"
                },
                {
                  "label": "Paid so far this year",
                  "value": 19000,
                  "fmt": "money"
                },
                {
                  "label": "Next payment (Q3, remaining quarters split the gap)",
                  "value": 16488,
                  "fmt": "money"
                },
                {
                  "label": "Penalty avoided (last year's, to ~2.5\u00d7 if income grows)",
                  "value": [
                    1100,
                    2750
                  ],
                  "fmt": "money_range"
                }
              ]
            }
          }
        ],
        "suppressed_below_materiality": [],
        "needs_context": [],
        "not_fired": [],
        "onboarding_gaps": [
          "income_trajectory",
          "health_coverage",
          "household_kids_ages",
          "planned_purchases"
        ]
      },
      "benchmark": {
        "estimate": 8400,
        "range": [
          5600,
          11100
        ],
        "left_on_table_last_year": 1100,
        "segment_label": "full-time solopreneurs, $50K\u2013$200K net",
        "note": "Segment-average first-year tax savings from a proactive plan \u2014 a rough estimate, not a personalized figure. Your real number comes from your plan after onboarding.",
        "math": {
          "route": "Segment average only: a proactive tax plan saves full-time solos roughly 3\u20136% of net profit in year one ($5,600\u2013$11,100 here). This is a benchmark, not your personalized number \u2014 that comes from your plan after a couple of questions.",
          "rows": [
            {
              "label": "Your 2025 net profit (Schedule C)",
              "value": 185000,
              "fmt": "money"
            },
            {
              "label": "Estimated first-year savings (midpoint of range)",
              "value": 8400,
              "fmt": "money"
            },
            {
              "label": "Underpayment penalty you paid last year",
              "value": 1100,
              "fmt": "money"
            }
          ]
        }
      },
      "whatif_grid": {
        "80000": {
          "q3_target": 0,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            1800,
            3700
          ],
          "retirement_range": [
            1200,
            1800
          ]
        },
        "85000": {
          "q3_target": 0,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            2100,
            4000
          ],
          "retirement_range": [
            1200,
            1900
          ]
        },
        "90000": {
          "q3_target": 0,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            2300,
            4300
          ],
          "retirement_range": [
            1200,
            2000
          ]
        },
        "95000": {
          "q3_target": 0,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            2500,
            4700
          ],
          "retirement_range": [
            2200,
            3900
          ]
        },
        "100000": {
          "q3_target": 105,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            2700,
            5000
          ],
          "retirement_range": [
            2200,
            4100
          ]
        },
        "105000": {
          "q3_target": 784,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            2900,
            5300
          ],
          "retirement_range": [
            2200,
            4300
          ]
        },
        "110000": {
          "q3_target": 1463,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            3100,
            5600
          ],
          "retirement_range": [
            2200,
            4500
          ]
        },
        "115000": {
          "q3_target": 2142,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            3300,
            6000
          ],
          "retirement_range": [
            2200,
            4700
          ]
        },
        "120000": {
          "q3_target": 2821,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            3500,
            6300
          ],
          "retirement_range": [
            2200,
            4900
          ]
        },
        "125000": {
          "q3_target": 3500,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            3700,
            6600
          ],
          "retirement_range": [
            2200,
            5100
          ]
        },
        "130000": {
          "q3_target": 4179,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            3900,
            6900
          ],
          "retirement_range": [
            2200,
            5300
          ]
        },
        "135000": {
          "q3_target": 4858,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            4100,
            7200
          ],
          "retirement_range": [
            2200,
            5500
          ]
        },
        "140000": {
          "q3_target": 5537,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            4400,
            7600
          ],
          "retirement_range": [
            2200,
            5700
          ]
        },
        "145000": {
          "q3_target": 6216,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            4600,
            7900
          ],
          "retirement_range": [
            2200,
            5900
          ]
        },
        "150000": {
          "q3_target": 6895,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            4800,
            8200
          ],
          "retirement_range": [
            2200,
            6100
          ]
        },
        "155000": {
          "q3_target": 7574,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            5000,
            8500
          ],
          "retirement_range": [
            2200,
            6300
          ]
        },
        "160000": {
          "q3_target": 8253,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            5200,
            8900
          ],
          "retirement_range": [
            2200,
            6500
          ]
        },
        "165000": {
          "q3_target": 8932,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            5400,
            9200
          ],
          "retirement_range": [
            2200,
            6700
          ]
        },
        "170000": {
          "q3_target": 9630,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            5600,
            9500
          ],
          "retirement_range": [
            2400,
            7600
          ]
        },
        "175000": {
          "q3_target": 10342,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            5800,
            9800
          ],
          "retirement_range": [
            2400,
            7800
          ]
        },
        "180000": {
          "q3_target": 11054,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            6000,
            10200
          ],
          "retirement_range": [
            2400,
            8000
          ]
        },
        "185000": {
          "q3_target": 11766,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            6200,
            10500
          ],
          "retirement_range": [
            2400,
            8300
          ]
        },
        "190000": {
          "q3_target": 12477,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            6500,
            10800
          ],
          "retirement_range": [
            2400,
            8500
          ]
        },
        "195000": {
          "q3_target": 13189,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            6700,
            11100
          ],
          "retirement_range": [
            2400,
            8700
          ]
        },
        "200000": {
          "q3_target": 13891,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            6800,
            11400
          ],
          "retirement_range": [
            2400,
            8900
          ]
        }
      },
      "hire_kid_per_kid": {
        "low_wage": 6000,
        "high_wage": 12000,
        "low": 2300,
        "high": 4600
      }
    },
    "theo": {
      "as_of": "2026-09-04",
      "customer": {
        "id": "theo",
        "name": "Theo Alvarez",
        "first_name": "Theo",
        "filing_status": "single",
        "state": "CO",
        "business": "Freelance photographer & videographer",
        "net_profit": 78000,
        "gross_receipts": 84500,
        "total_tax": 15670,
        "balance_due": 3670,
        "penalty": 280,
        "filed_date": "2026-04-10",
        "product": "TurboTax Self-Employed",
        "hook": {
          "channel": "email",
          "copy": "Your Q3 payment is coming up \u2014 and you mentioned new gear this year. Let's make that purchase work for you before Dec 31. See your plan \u2192"
        }
      },
      "analysis": {
        "customer": "theo",
        "name": "Theo Alvarez",
        "as_of": "2026-09-04",
        "tax_year_planning": 2026,
        "shown": [
          {
            "strategy": "retirement-optimization",
            "label": "Retirement contribution (SEP / Solo 401(k))",
            "fires": true,
            "needs_context": false,
            "reason": "$0 contributed against ~$14,498 of SEP headroom",
            "range": [
              1200,
              1700
            ],
            "range_kind": "deferral_not_permanent",
            "deadline": "2026-12-31",
            "deadline_note": "The plan must exist by Dec 31 \u2014 months before filing would ever show you this. (SEP contributions can land by the filing deadline.)",
            "door": "guided setup; expert optional for plan choice",
            "detail": {
              "marginal_rate": 0.12,
              "headroom": {
                "sep_max": 14498,
                "solo401k_max": 38998
              },
              "levels": [
                {
                  "contribution": 10000,
                  "tax_deferred_this_year": 1200,
                  "monthly_set_aside_rest_of_year": 1667
                },
                {
                  "contribution": 14498,
                  "tax_deferred_this_year": 1700,
                  "monthly_set_aside_rest_of_year": 2416
                }
              ]
            },
            "math": {
              "route": "Contribution \u00d7 your marginal tax rate = tax deferred this year. Deferral, not free money \u2014 tax is paid later on withdrawal.",
              "rows": [
                {
                  "label": "Net profit (Schedule C, 2025)",
                  "value": 78000,
                  "fmt": "money"
                },
                {
                  "label": "SEP headroom (~20% of profit less \u00bd SE tax)",
                  "value": 14498,
                  "fmt": "money"
                },
                {
                  "label": "Solo 401(k) headroom (adds employee deferral)",
                  "value": 38998,
                  "fmt": "money"
                },
                {
                  "label": "Contributed so far",
                  "value": 0,
                  "fmt": "money"
                },
                {
                  "label": "Your marginal rate",
                  "value": 0.12,
                  "fmt": "pct"
                },
                {
                  "label": "Smallest level: $10,000 \u00d7 rate",
                  "value": 1200,
                  "fmt": "money"
                },
                {
                  "label": "Max SEP level: $14,498 \u00d7 rate",
                  "value": 1700,
                  "fmt": "money"
                },
                {
                  "label": "Deferred this year (range)",
                  "value": [
                    1200,
                    1700
                  ],
                  "fmt": "money_range"
                }
              ]
            },
            "framing_required": "Deferral, not free money \u2014 tax is paid later on withdrawal, not erased."
          },
          {
            "strategy": "quarterly-estimates",
            "label": "Quarterly safe-harbor payments",
            "fires": true,
            "needs_context": false,
            "reason": "$280 underpayment penalty and $3,670 balance due on the TY25 return",
            "range": [
              280,
              700
            ],
            "range_kind": "penalty_avoided",
            "action_amount": 4835,
            "deadline": "2026-09-15",
            "door": "self-serve (IRS Direct Pay) + reminder",
            "detail": {
              "safe_harbor_total": 15670,
              "assumed_withholding": 0,
              "needed_via_estimates": 15670,
              "route": "100% of last year's tax",
              "per_quarter": 3918,
              "quarters": [
                {
                  "q": 1,
                  "due": "2026-04-15",
                  "target": 3918,
                  "paid": 3000,
                  "status": "missed"
                },
                {
                  "q": 2,
                  "due": "2026-06-15",
                  "target": 3918,
                  "paid": 3000,
                  "status": "missed"
                },
                {
                  "q": 3,
                  "due": "2026-09-15",
                  "target": 4835,
                  "paid": 0,
                  "status": "due"
                },
                {
                  "q": 4,
                  "due": "2027-01-15",
                  "target": 4835,
                  "paid": 0,
                  "status": "due"
                }
              ],
              "next": {
                "q": 3,
                "due": "2026-09-15",
                "target": 4835,
                "paid": 0,
                "status": "due"
              },
              "missed": [
                {
                  "q": 1,
                  "due": "2026-04-15",
                  "target": 3918,
                  "paid": 3000,
                  "status": "missed"
                },
                {
                  "q": 2,
                  "due": "2026-06-15",
                  "target": 3918,
                  "paid": 3000,
                  "status": "missed"
                }
              ],
              "withholding_note": "No W-2 withholding on the return \u2014 estimates carry the whole safe harbor."
            },
            "math": {
              "route": "Cheapest penalty-proof total = the safe-harbor % of last year's tax. Withholding and payments already made count; remaining quarters split what's left.",
              "rows": [
                {
                  "label": "Last year's total tax (2025 return)",
                  "value": 15670,
                  "fmt": "money"
                },
                {
                  "label": "Safe-harbor route",
                  "value": "100% of last year's tax",
                  "fmt": "text"
                },
                {
                  "label": "Penalty-proof total for the year",
                  "value": 15670,
                  "fmt": "money"
                },
                {
                  "label": "W-2 withholding assumed (counts toward it)",
                  "value": 0,
                  "fmt": "money"
                },
                {
                  "label": "Needed via estimated payments",
                  "value": 15670,
                  "fmt": "money"
                },
                {
                  "label": "Paid so far this year",
                  "value": 6000,
                  "fmt": "money"
                },
                {
                  "label": "Next payment (Q3, remaining quarters split the gap)",
                  "value": 4835,
                  "fmt": "money"
                },
                {
                  "label": "Penalty avoided (last year's, to ~2.5\u00d7 if income grows)",
                  "value": [
                    280,
                    700
                  ],
                  "fmt": "money_range"
                }
              ]
            }
          },
          {
            "strategy": "deduction-optimization",
            "label": "Deduction tracking (bank connect)",
            "fires": true,
            "needs_context": false,
            "reason": "Expenses run 8% of revenue; solo services business businesses typically run ~12%",
            "range": null,
            "range_kind": "gated_no_presize",
            "gated": true,
            "gate_rule": "Never show a $ range from the return alone. The pitch is the gap + the connect.",
            "deadline": null,
            "door": "bank connect via E3B Lite (free)",
            "math": {
              "route": "No dollar range by design \u2014 the return only shows what made it in, so what's missing can't be sized from it. The gap vs. benchmark is the signal; connecting the bank gets the real number.",
              "rows": [
                {
                  "label": "Business expenses claimed (Schedule C)",
                  "value": 6500,
                  "fmt": "money"
                },
                {
                  "label": "Gross receipts",
                  "value": 84500,
                  "fmt": "money"
                },
                {
                  "label": "Your expense ratio",
                  "value": 0.077,
                  "fmt": "pct"
                },
                {
                  "label": "Typical for solo services business",
                  "value": 0.12,
                  "fmt": "pct"
                },
                {
                  "label": "Lines claimed at $0",
                  "value": "vehicle mileage, home office, equipment",
                  "fmt": "text"
                }
              ]
            },
            "detail": {
              "expense_ratio": 0.077,
              "benchmark_ratio": 0.12,
              "benchmark_label": "Solo services business",
              "zero_claimed_lines": [
                "vehicle mileage",
                "home office",
                "equipment"
              ],
              "commonly_missed": [
                "home office",
                "business mileage",
                "software and subscriptions",
                "phone and internet",
                "self-employed health insurance premiums"
              ],
              "se_health_note": "Marketplace premiums not claimed as SE health deduction"
            }
          }
        ],
        "suppressed_below_materiality": [],
        "needs_context": [
          {
            "strategy": "hire-your-kid",
            "context_needed": "household \u2014 kids and ages (onboarding question)"
          }
        ],
        "not_fired": [
          {
            "strategy": "s-corp-election",
            "reason": "Net profit $78,000 is below the $80,000 threshold where the split beats the overhead"
          }
        ],
        "onboarding_gaps": [
          "income_trajectory",
          "health_coverage",
          "household_kids_ages"
        ]
      },
      "benchmark": {
        "estimate": 3500,
        "range": [
          2300,
          4700
        ],
        "left_on_table_last_year": 280,
        "segment_label": "full-time solopreneurs, $50K\u2013$200K net",
        "note": "Segment-average first-year tax savings from a proactive plan \u2014 a rough estimate, not a personalized figure. Your real number comes from your plan after onboarding.",
        "math": {
          "route": "Segment average only: a proactive tax plan saves full-time solos roughly 3\u20136% of net profit in year one ($2,300\u2013$4,700 here). This is a benchmark, not your personalized number \u2014 that comes from your plan after a couple of questions.",
          "rows": [
            {
              "label": "Your 2025 net profit (Schedule C)",
              "value": 78000,
              "fmt": "money"
            },
            {
              "label": "Estimated first-year savings (midpoint of range)",
              "value": 3500,
              "fmt": "money"
            },
            {
              "label": "Underpayment penalty you paid last year",
              "value": 280,
              "fmt": "money"
            }
          ]
        }
      },
      "whatif_grid": {
        "80000": {
          "q3_target": 4256,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            1800,
            3700
          ],
          "retirement_range": [
            1200,
            1800
          ]
        },
        "85000": {
          "q3_target": 4771,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            2100,
            4000
          ],
          "retirement_range": [
            1200,
            1900
          ]
        },
        "90000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            2300,
            4300
          ],
          "retirement_range": [
            1200,
            2000
          ]
        },
        "95000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            2500,
            4700
          ],
          "retirement_range": [
            2200,
            3900
          ]
        },
        "100000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            2700,
            5000
          ],
          "retirement_range": [
            2200,
            4100
          ]
        },
        "105000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            2900,
            5300
          ],
          "retirement_range": [
            2200,
            4300
          ]
        },
        "110000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            3100,
            5600
          ],
          "retirement_range": [
            2200,
            4500
          ]
        },
        "115000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            3300,
            6000
          ],
          "retirement_range": [
            2200,
            4700
          ]
        },
        "120000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            3500,
            6300
          ],
          "retirement_range": [
            2200,
            4900
          ]
        },
        "125000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            3700,
            6600
          ],
          "retirement_range": [
            2200,
            5100
          ]
        },
        "130000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            3900,
            6900
          ],
          "retirement_range": [
            2200,
            5300
          ]
        },
        "135000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            4100,
            7200
          ],
          "retirement_range": [
            2200,
            5500
          ]
        },
        "140000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            4400,
            7600
          ],
          "retirement_range": [
            2200,
            5700
          ]
        },
        "145000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            4600,
            7900
          ],
          "retirement_range": [
            2200,
            5900
          ]
        },
        "150000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            4800,
            8200
          ],
          "retirement_range": [
            2200,
            6100
          ]
        },
        "155000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            5000,
            8500
          ],
          "retirement_range": [
            2200,
            6300
          ]
        },
        "160000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            5200,
            8900
          ],
          "retirement_range": [
            2200,
            6500
          ]
        },
        "165000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            5400,
            9200
          ],
          "retirement_range": [
            2200,
            6700
          ]
        },
        "170000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            5600,
            9500
          ],
          "retirement_range": [
            2400,
            7600
          ]
        },
        "175000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            5800,
            9800
          ],
          "retirement_range": [
            2400,
            7800
          ]
        },
        "180000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            6000,
            10200
          ],
          "retirement_range": [
            2400,
            8000
          ]
        },
        "185000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            6200,
            10500
          ],
          "retirement_range": [
            2400,
            8300
          ]
        },
        "190000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            6500,
            10800
          ],
          "retirement_range": [
            2400,
            8500
          ]
        },
        "195000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            6700,
            11100
          ],
          "retirement_range": [
            2400,
            8700
          ]
        },
        "200000": {
          "q3_target": 4835,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            6800,
            11400
          ],
          "retirement_range": [
            2400,
            8900
          ]
        }
      },
      "hire_kid_per_kid": {
        "low_wage": 6000,
        "high_wage": 12000,
        "low": 1600,
        "high": 3100
      }
    },
    "gabriela": {
      "as_of": "2026-09-04",
      "customer": {
        "id": "gabriela",
        "name": "Gabriela Santos",
        "first_name": "Gabriela",
        "filing_status": "married_filing_jointly",
        "state": "FL",
        "business": "Handmade jewelry & goods (online shop)",
        "net_profit": 120000,
        "gross_receipts": 131000,
        "total_tax": 31750,
        "balance_due": -50,
        "penalty": 0,
        "filed_date": "2026-03-30",
        "product": "TurboTax Self-Employed",
        "hook": {
          "channel": "post_file_transition",
          "copy": "Your withholding kept you penalty-free this year \u2014 nice. Now let's turn $120K of shop profit into next year's savings. See your plan \u2192"
        }
      },
      "analysis": {
        "customer": "gabriela",
        "name": "Gabriela Santos",
        "as_of": "2026-09-04",
        "tax_year_planning": 2026,
        "shown": [
          {
            "strategy": "hire-your-kid",
            "label": "Hire your child",
            "fires": true,
            "needs_context": false,
            "reason": "2 kid(s) in the FICA-exempt window (7\u201317) on a sole prop",
            "range": [
              4400,
              8600
            ],
            "range_kind": "recurring_annual",
            "deadline": null,
            "deadline_note": "Wages must be paid in-year for in-year deduction",
            "door": "expert (payroll setup + documentation)",
            "detail": {
              "eligible_ages": [
                9,
                13
              ],
              "wage_guidance": [
                6000,
                12000
              ],
              "max_wage_no_income_tax": 16100
            },
            "math": {
              "route": "Wages for real work are a business deduction: you save your marginal rate + SE tax on the shifted profit; the child owes ~$0 under the standard deduction, and no FICA under 18 on a parent's sole prop.",
              "rows": [
                {
                  "label": "Kids in the 7\u201317 window",
                  "value": "2 (ages 9, 13)",
                  "fmt": "text"
                },
                {
                  "label": "Typical defensible wage per kid",
                  "value": [
                    6000,
                    12000
                  ],
                  "fmt": "money_range"
                },
                {
                  "label": "Your marginal rate",
                  "value": 0.22,
                  "fmt": "pct"
                },
                {
                  "label": "Effective SE rate avoided",
                  "value": 0.1412955,
                  "fmt": "pct"
                },
                {
                  "label": "Savings per kid (wage \u00d7 combined rate)",
                  "value": [
                    2200,
                    4300
                  ],
                  "fmt": "money_range"
                },
                {
                  "label": "Across 2 kid(s), per year",
                  "value": [
                    4400,
                    8600
                  ],
                  "fmt": "money_range"
                }
              ]
            },
            "costs_unprompted": [
              "the work must be real and the wage defensible for the child's age",
              "timesheets and a payroll record are what make it stick in an audit"
            ]
          },
          {
            "strategy": "s-corp-election",
            "label": "Elect S-Corp (reasonable comp split)",
            "fires": true,
            "needs_context": false,
            "reason": "Net profit $120,000 \u2014 all of it paid 15.3% SE tax as a sole prop",
            "range": [
              3500,
              6300
            ],
            "range_kind": "recurring_annual",
            "deadline": "2027-03-15",
            "deadline_note": "2026 window passed (Mar 16) \u2014 election would be set up for tax year 2027",
            "door": "expert (reasonable-comp analysis + election filing)",
            "expert_gated": true,
            "detail": {
              "se_tax_today": 16955,
              "salary_band": [
                60000,
                78000
              ],
              "friction_cost": 1500,
              "savings_range": [
                3500,
                6300
              ]
            },
            "math": {
              "route": "SE tax you pay today, minus payroll tax on a reasonable salary, minus payroll/filing friction \u2014 computed at both ends of the salary band. Higher salary \u2192 smaller saving.",
              "rows": [
                {
                  "label": "Net profit (Schedule C, 2025)",
                  "value": 120000,
                  "fmt": "money"
                },
                {
                  "label": "SE tax today (15.3% on 92.35% of profit)",
                  "value": 16955,
                  "fmt": "money"
                },
                {
                  "label": "Reasonable-salary band (50\u201365% of profit)",
                  "value": [
                    60000,
                    78000
                  ],
                  "fmt": "money_range"
                },
                {
                  "label": "Payroll tax across that band",
                  "value": [
                    9180,
                    11934
                  ],
                  "fmt": "money_range"
                },
                {
                  "label": "Annual payroll + filing friction (netted out)",
                  "value": 1500,
                  "fmt": "money"
                },
                {
                  "label": "Savings range (recurring, annual)",
                  "value": [
                    3500,
                    6300
                  ],
                  "fmt": "money_range"
                }
              ]
            },
            "costs_unprompted": [
              "monthly payroll to run",
              "a separate business return (1120-S)",
              "IRS watches for a defensible 'reasonable salary'",
              "~$1,500/yr payroll + filing friction (already netted out of the range)"
            ]
          },
          {
            "strategy": "retirement-optimization",
            "label": "Retirement contribution (SEP / Solo 401(k))",
            "fires": true,
            "needs_context": false,
            "reason": "$0 contributed against ~$22,304 of SEP headroom",
            "range": [
              2200,
              4900
            ],
            "range_kind": "deferral_not_permanent",
            "deadline": "2026-12-31",
            "deadline_note": "The plan must exist by Dec 31 \u2014 months before filing would ever show you this. (SEP contributions can land by the filing deadline.)",
            "door": "guided setup; expert optional for plan choice",
            "detail": {
              "marginal_rate": 0.22,
              "headroom": {
                "sep_max": 22304,
                "solo401k_max": 46804
              },
              "levels": [
                {
                  "contribution": 10000,
                  "tax_deferred_this_year": 2200,
                  "monthly_set_aside_rest_of_year": 1667
                },
                {
                  "contribution": 20000,
                  "tax_deferred_this_year": 4400,
                  "monthly_set_aside_rest_of_year": 3333
                },
                {
                  "contribution": 22304,
                  "tax_deferred_this_year": 4900,
                  "monthly_set_aside_rest_of_year": 3717
                }
              ]
            },
            "math": {
              "route": "Contribution \u00d7 your marginal tax rate = tax deferred this year. Deferral, not free money \u2014 tax is paid later on withdrawal.",
              "rows": [
                {
                  "label": "Net profit (Schedule C, 2025)",
                  "value": 120000,
                  "fmt": "money"
                },
                {
                  "label": "SEP headroom (~20% of profit less \u00bd SE tax)",
                  "value": 22304,
                  "fmt": "money"
                },
                {
                  "label": "Solo 401(k) headroom (adds employee deferral)",
                  "value": 46804,
                  "fmt": "money"
                },
                {
                  "label": "Contributed so far",
                  "value": 0,
                  "fmt": "money"
                },
                {
                  "label": "Your marginal rate",
                  "value": 0.22,
                  "fmt": "pct"
                },
                {
                  "label": "Smallest level: $10,000 \u00d7 rate",
                  "value": 2200,
                  "fmt": "money"
                },
                {
                  "label": "Max SEP level: $22,304 \u00d7 rate",
                  "value": 4900,
                  "fmt": "money"
                },
                {
                  "label": "Deferred this year (range)",
                  "value": [
                    2200,
                    4900
                  ],
                  "fmt": "money_range"
                }
              ]
            },
            "framing_required": "Deferral, not free money \u2014 tax is paid later on withdrawal, not erased."
          },
          {
            "strategy": "deduction-optimization",
            "label": "Deduction tracking (bank connect)",
            "fires": true,
            "needs_context": false,
            "reason": "Expenses run 8% of revenue; solo services business businesses typically run ~12%",
            "range": null,
            "range_kind": "gated_no_presize",
            "gated": true,
            "gate_rule": "Never show a $ range from the return alone. The pitch is the gap + the connect.",
            "deadline": null,
            "door": "bank connect via E3B Lite (free)",
            "math": {
              "route": "No dollar range by design \u2014 the return only shows what made it in, so what's missing can't be sized from it. The gap vs. benchmark is the signal; connecting the bank gets the real number.",
              "rows": [
                {
                  "label": "Business expenses claimed (Schedule C)",
                  "value": 11000,
                  "fmt": "money"
                },
                {
                  "label": "Gross receipts",
                  "value": 131000,
                  "fmt": "money"
                },
                {
                  "label": "Your expense ratio",
                  "value": 0.084,
                  "fmt": "pct"
                },
                {
                  "label": "Typical for solo services business",
                  "value": 0.12,
                  "fmt": "pct"
                },
                {
                  "label": "Lines claimed at $0",
                  "value": "vehicle mileage, home office",
                  "fmt": "text"
                }
              ]
            },
            "detail": {
              "expense_ratio": 0.084,
              "benchmark_ratio": 0.12,
              "benchmark_label": "Solo services business",
              "zero_claimed_lines": [
                "vehicle mileage",
                "home office"
              ],
              "commonly_missed": [
                "home office",
                "business mileage",
                "software and subscriptions",
                "phone and internet",
                "self-employed health insurance premiums"
              ],
              "se_health_note": null
            }
          }
        ],
        "suppressed_below_materiality": [],
        "needs_context": [],
        "not_fired": [
          {
            "strategy": "quarterly-estimates",
            "reason": "No penalty and balance due under $1,000 \u2014 estimates look on track"
          }
        ],
        "onboarding_gaps": [
          "income_trajectory",
          "health_coverage",
          "household_kids_ages",
          "planned_purchases"
        ]
      },
      "benchmark": {
        "estimate": 5400,
        "range": [
          3600,
          7200
        ],
        "left_on_table_last_year": 0,
        "segment_label": "full-time solopreneurs, $50K\u2013$200K net",
        "note": "Segment-average first-year tax savings from a proactive plan \u2014 a rough estimate, not a personalized figure. Your real number comes from your plan after onboarding.",
        "math": {
          "route": "Segment average only: a proactive tax plan saves full-time solos roughly 3\u20136% of net profit in year one ($3,600\u2013$7,200 here). This is a benchmark, not your personalized number \u2014 that comes from your plan after a couple of questions.",
          "rows": [
            {
              "label": "Your 2025 net profit (Schedule C)",
              "value": 120000,
              "fmt": "money"
            },
            {
              "label": "Estimated first-year savings (midpoint of range)",
              "value": 5400,
              "fmt": "money"
            }
          ]
        }
      },
      "whatif_grid": {
        "80000": {
          "q3_target": 0,
          "q3_due": null,
          "s_corp_range": [
            1800,
            3700
          ],
          "retirement_range": [
            1200,
            1800
          ]
        },
        "85000": {
          "q3_target": 0,
          "q3_due": null,
          "s_corp_range": [
            2100,
            4000
          ],
          "retirement_range": [
            1200,
            1900
          ]
        },
        "90000": {
          "q3_target": 0,
          "q3_due": null,
          "s_corp_range": [
            2300,
            4300
          ],
          "retirement_range": [
            1200,
            2000
          ]
        },
        "95000": {
          "q3_target": 0,
          "q3_due": null,
          "s_corp_range": [
            2500,
            4700
          ],
          "retirement_range": [
            1200,
            2100
          ]
        },
        "100000": {
          "q3_target": 0,
          "q3_due": null,
          "s_corp_range": [
            2700,
            5000
          ],
          "retirement_range": [
            1200,
            2200
          ]
        },
        "105000": {
          "q3_target": 0,
          "q3_due": null,
          "s_corp_range": [
            2900,
            5300
          ],
          "retirement_range": [
            2200,
            4300
          ]
        },
        "110000": {
          "q3_target": 0,
          "q3_due": null,
          "s_corp_range": [
            3100,
            5600
          ],
          "retirement_range": [
            2200,
            4500
          ]
        },
        "115000": {
          "q3_target": 0,
          "q3_due": null,
          "s_corp_range": [
            3300,
            6000
          ],
          "retirement_range": [
            2200,
            4700
          ]
        },
        "120000": {
          "q3_target": 0,
          "q3_due": null,
          "s_corp_range": [
            3500,
            6300
          ],
          "retirement_range": [
            2200,
            4900
          ]
        },
        "125000": {
          "q3_target": 0,
          "q3_due": null,
          "s_corp_range": [
            3700,
            6600
          ],
          "retirement_range": [
            2200,
            5100
          ]
        },
        "130000": {
          "q3_target": 0,
          "q3_due": null,
          "s_corp_range": [
            3900,
            6900
          ],
          "retirement_range": [
            2200,
            5300
          ]
        },
        "135000": {
          "q3_target": 424,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            4100,
            7200
          ],
          "retirement_range": [
            2200,
            5500
          ]
        },
        "140000": {
          "q3_target": 1103,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            4400,
            7600
          ],
          "retirement_range": [
            2200,
            5700
          ]
        },
        "145000": {
          "q3_target": 1562,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            4600,
            7900
          ],
          "retirement_range": [
            2200,
            5900
          ]
        },
        "150000": {
          "q3_target": 1562,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            4800,
            8200
          ],
          "retirement_range": [
            2200,
            6100
          ]
        },
        "155000": {
          "q3_target": 1562,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            5000,
            8500
          ],
          "retirement_range": [
            2200,
            6300
          ]
        },
        "160000": {
          "q3_target": 1562,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            5200,
            8900
          ],
          "retirement_range": [
            2200,
            6500
          ]
        },
        "165000": {
          "q3_target": 1562,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            5400,
            9200
          ],
          "retirement_range": [
            2200,
            6700
          ]
        },
        "170000": {
          "q3_target": 1562,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            5600,
            9500
          ],
          "retirement_range": [
            2200,
            7000
          ]
        },
        "175000": {
          "q3_target": 1562,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            5800,
            9800
          ],
          "retirement_range": [
            2200,
            7200
          ]
        },
        "180000": {
          "q3_target": 1562,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            6000,
            10200
          ],
          "retirement_range": [
            2200,
            7400
          ]
        },
        "185000": {
          "q3_target": 1562,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            6200,
            10500
          ],
          "retirement_range": [
            2200,
            7600
          ]
        },
        "190000": {
          "q3_target": 1562,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            6500,
            10800
          ],
          "retirement_range": [
            2200,
            7800
          ]
        },
        "195000": {
          "q3_target": 1562,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            6700,
            11100
          ],
          "retirement_range": [
            2200,
            8000
          ]
        },
        "200000": {
          "q3_target": 1562,
          "q3_due": "2026-09-15",
          "s_corp_range": [
            6800,
            11400
          ],
          "retirement_range": [
            2200,
            8200
          ]
        }
      },
      "hire_kid_per_kid": {
        "low_wage": 6000,
        "high_wage": 12000,
        "low": 2200,
        "high": 4300
      }
    }
  }
};
